### ISSUE TITLE
Update dockerfile

### ISSUE THREAD

**Issue by dhood** [ros-infrastructure/rosindex#1]

**Comment by sloretz** [comment]
Summarizing an offline conversation with @dhood, It looks like the dockerfile in https://github.com/rosindex/containers works as is with the changes made to this repo. The acceptance criteria for this task is script that can be used by the buildfarm to generate and deploy the website.

**Comment by chapulina** [comment]
@hidmic , do you think we can close this one?

**Comment by hidmic** [comment]
Yeah, it's clearly outdated. Thanks for raising it @chapulina.
