### ISSUE TITLE
Add the ability to prune old files

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/rosindex#106]
We added in #105 to add new files and removes deleted ones, But I don't think we have anything that will delete old files before they are added to the git repository for uploading. So they'll never be removed.

**Comment by chapulina** [comment]
Maybe something like this could do the trick:

~~~
cd <path to index.ros.org clone>
rm -rf *
cp <path to temp dir where site was generated> <path to index.ros.org clone> -r
git add -u --all # -u should "git rm" tracked files that were deleted, --all should add new untracked files
git commit ...
~~~

**Comment by tfoote** [comment]
That seems like a good approach.
Note: I believe that `--all` implies `-u` as well as `*`. https://stackoverflow.com/questions/572549/difference-between-git-add-a-and-git-add

**Comment by hidmic** [comment]
Is this a convenience for rosindex developers? The [buildfarm job mounts the `index.ros.org` clone](https://github.com/ros-infrastructure/ros_buildfarm/blob/master/ros_buildfarm/templates/doc/doc_independent_docker_job.xml.em#L115) for Jekyll to access it i.e. nuke it on site build (see [`keep_files` configuration option](https://jekyllrb.com/docs/configuration/options/#global-configuration)).

**Comment by tfoote** [comment]
If jekyll clears the files we just need to make sure that they also get git rm'd and committed. By default if you just delete files without using `git rm` or `git add missing.file` they will still be in the commit despite being removed from the local workspace. If my closer reading of --all automaticallly also does `git rm` for missing files then we can close this as resolved by #105

**Comment by hidmic** [comment]
Per `git add` man pages:

```
-A, --all, --no-ignore-removal
  Update the index not only where the working tree has a file matching <pathspec> but also where the
  index already has an entry. This adds, modifies, and removes index entries to match the working tree.

  If no <pathspec> is given when -A option is used, all files in the entire working tree are updated
  (old versions of Git used to limit the update to the current directory and its subdirectories).
```

The third alias for the cli option is somewhat explicit :).

**Comment by hidmic** [comment]
@tfoote are you OK with closing this one too?

**Comment by tfoote** [comment]
yeah, I think we're all set for this.
