### ISSUE TITLE
Minimize git diff on upload

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/rosindex#108]
When we push a new version of  the site the git diff is too large to render, even if most things have changed. We should find out what sort of trivial changes are happening to files (such as timestamps embedded) and revert these trivial changes before committing the changes to the repository.  As suggested here: https://github.com/ros-infrastructure/ros_buildfarm_config/pull/123#issuecomment-432876488

An iterator that checks the diff could relatively easily be inserted before the add logic in this suggestion: https://github.com/ros-infrastructure/rosindex/issues/106#issuecomment-433546907 that would revert the files with trivial/non-content changes in the diffs.

**Comment by hidmic** [comment]
@tfoote would it make sense to prevent non-content changes from getting generated in the first place?

**Comment by tfoote** [comment]
Yeah, the biggest problem is to have traceability as to when a page was last generated. The date stamp in the bottom is super valuable for that mechanism. If we can provide that sort of tracibility in another way that would be great. But it should be clear to a user if recent changes have been included or not. Especially since we only run the rebuild periodically. Though if we can know that everything was generated in each rebuild with good cleanup then we could probably pull that out and know that from a single timestamp on a main page.

**Comment by dirk-thomas** [comment]
Individual page timestamps are nice and not really a problem. They should just not be the only change to a page. So the semantic of the timestamp would be "last change" rather then "last generated".
