### ISSUE TITLE
venn.js missing on deployed site

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/rosindex#110]
When visiting https://index.ros.org/stats/

I get `Failed to load resource: the server responded with a status of 404 ()` on the console
![image](https://user-images.githubusercontent.com/447804/47596821-f3b8b100-d93d-11e8-9a2c-55d48a5bf2fa.png)

I believe that this is due to a non-recursive clone of rosindex. This might be something that needs to be resolved in the ros_buildfarm repository for the checkout.

**Comment by hidmic** [comment]
@tfoote would it make sense to replace the submodule with a subtree?

**Comment by tfoote** [comment]
Yeah, a subtree might be a good solution or we could just copy it into the repository, we don't really need the full history in our repository and keeping it pinned seems reasonable, We can then choose to update it manually when/if we want a newer version.
