### ISSUE TITLE
Provide support for pulling Sphinx projects

### ISSUE THREAD

**Issue by hidmic** [ros-infrastructure/rosindex#112]
Connected to ros2/ros2_documentation#10. As @wjwwood suggested, it'd make for a much better contributor experience if the external documentation repos from which we pull content from were Sphinx documentation projects themselves. This requires a slight change on the `docs_generator.rb` plugin, to make it rely on an existing Sphinx scaffold instead of providing it own.

**Comment by hidmic** [comment]
@tfoote @chapulina there's a detail about this that we've been ignoring so far. We're currently dropping any Sphinx provided stylesheets in lieu of Jekyll's. This may result in an _rosindexed_ external documentation looking significantly different compared to what a potential contributor sees locally. 

Thoughts on how we want to approach this?

**Comment by chapulina** [comment]
I *suspect* the most important thing a contributor would like to check is whether the RST is properly converted to HTML elements. So if images, tables, links, etc are properly parsed.

The styling details are probably less important. Think how a markdown file may be displayed differently by Github or Bitbucket or your local viewer...

**Comment by wjwwood** [comment]
The style is definitely not the most important thing, but it would be nice to have. I'm not sure how it could be accomplished, so I'd say it's fine to have it look different than the live site.

Read the Docs provides a sphinx theme for local testing(https://pypi.org/project/sphinx_rtd_theme/), long term that might be the thing to do, but I don't know how you'd keep it in sync with the Jekyll styles.

**Comment by hidmic** [comment]
Addressed already. Closing this one.
