### ISSUE TITLE
search results incomplete

### ISSUE THREAD

**Issue by dirk-thomas** [ros-infrastructure/rosindex#113]
I tried to search for `ROS_DOMAIN_ID` but the result list is empty even though there are multiple pages containing that term.

* https://index.ros.org/doc/ros2/Linux-Development-Setup/#multiple-host-interference
* https://index.ros.org/doc/ros2/Overview-of-ROS-2-concepts/#discovery
* https://index.ros.org/doc/ros2/ROS-2-On-boarding-Guide/#choose-a-dds-domain-id
* https://index.ros.org/doc/ros2/Set-up-a-new-macOS-CI-node/#ros-2-ci-host-setup

**Comment by dirk-thomas** [comment]
The current search only considers the package metadata and not any of the static content. Therefore we need (another?) way to search through that part of https://index.ros.org/doc/*

**Comment by tfoote** [comment]
When looking into extending this the search also doesn't cover the rosdep keys.

**Comment by dirk-thomas** [comment]
I don't mind how this is addressed. Even a second search form which just brings me to a google search limited to the site is better than nothing.
