### ISSUE TITLE
Add the standard ROS header above all the pages

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/rosindex#116]
There's a standard ROS header that we put on all sites to enable quickly getting to other resources. It's just text and one line but is quite convenient. 

![image](https://user-images.githubusercontent.com/447804/48295800-7cf2dc00-e444-11e8-998a-78678fa0fc75.png)

On Discourse it's just in the header.
```
<div align="center">
      <br>
      <table id="topnav-table">
        <tr>
          <td valign="middle">
              ROS Resources: 
            <a href="http://wiki.ros.org/">Documentation</a>
            |
            <a href="http://wiki.ros.org/Support">Support</a>
            |
            <a href="http://discourse.ros.org/">Discussion Forum</a>
            |
            <a href="http://status.ros.org/">Service Status</a>
            |
            <a href="http://answers.ros.org/">Q&A answers.ros.org</a>

          </td>

      </tr>
    </table> <!-- topnav-table -->
</div>
```

**Comment by hidmic** [comment]
Sounds like a good idea, though I'm a bit wary about having a `Documentation` link that takes one to the wiki. Isn't it pure ROS (1, not 2)?

**Comment by tfoote** [comment]
We can review and update the links in the future. Likely that will turn back here/be removed in the long run. But for now I just want to have all the defaults for people finding things. The wiki is still somewhere that the majority of users will want to go.

**Comment by apojomovsky** [comment]
Hi @tfoote , any preference regarding the v-position at which the bar should be placed?
Personally, I think the second one might look a bit less congested than the other.
1)
![screenshot from 2018-11-15 15-46-51](https://user-images.githubusercontent.com/5348967/48574530-2e36bd80-e8ee-11e8-8fde-4e79e46dd748.png)
2)
![screenshot from 2018-11-15 15-37-39](https://user-images.githubusercontent.com/5348967/48574532-2ecf5400-e8ee-11e8-8f1e-2aaf5ea3b601.png)

**Comment by tfoote** [comment]
It is a little congested at the top. But that's consistent with all the other sites and if there are long web pages(such as the listings or almost any package with documentation) the footer isn't usually visible so the utility of the quick links goes down. I think it's better to keep it at the top. We could integrate it into the header more like the wiki, but for the short term I think the simple separate elements are good enough.
