### ISSUE TITLE
Crawl non-package specific documentation repositories

### ISSUE THREAD

**Issue by hidmic** [ros-infrastructure/rosindex#12]
We'd want non-package specific documentation content (e.g. ROS install instructions) to show up in the rosindex too, preferably at `/doc`. To that end, documentation repositories need to be:

- [ ] Listed in a VCS repos file within rosindex repo.
- [ ] Pulled into Jekyll crawling path using VCS.

Generated content in turn needs to be made accessible through the site.

**Comment by hidmic** [comment]
@tfoote do these repositories exist already?

**Comment by tfoote** [comment]
These repos don't exist yet.
