### ISSUE TITLE
Add Crystal

### ISSUE THREAD

**Issue by chapulina** [ros-infrastructure/rosindex#120]
Currently, packages only have up to the Bouncy version listed, for example:

https://index.ros.org/p/rviz_common/github-ros2-rviz/

Since we're parsing rosdistro files, I think we can already add crystal?

**Comment by nuclearsandwich** [comment]
> Since we're parsing rosdistro files, I think we can already add crystal?

It would be neat if the [prerelease](https://github.com/ros2/rosdistro/blob/3da75ec4eed9fb19d03672517828ef1f0793d238/index-v4.yaml#L25) status was taken into account somehow.

**Comment by tfoote** [comment]
@nuclearsandwich good idea. I ticketed that in #123 since that's a much bigger change than #121
