### ISSUE TITLE
index of all pages

### ISSUE THREAD

**Issue by chapulina** [ros-infrastructure/rosindex#122]
By @dirk-thomas in https://github.com/ros-infrastructure/index.ros.org/issues/1

It would be good to generate an index of all the available pages under e.g. https://index.ros.org/doc/ros2/

Currently I find myself going to the old GitHub wiki which has that index and then following the link to index.ros.org.

**Comment by nuclearsandwich** [comment]
This has been a frequent item of discussion across the team and something we'd all like to see. :zap: to @chapulina for opening the issue.

**Comment by chapulina** [comment]
I'd love to take credit, but I was just moving @dirk-thomas 's issue :wink:

**Comment by hidmic** [comment]
I'd think #79 would eventually somewhat deal with uneasy and hard to find documentation pages. At least it'd make the search a bit more intuitive.

I tried adding an index to the main page. It gets a *little bit* large, to put it mildly. What do you think about skipping such an index and working towards https://github.com/ros-infrastructure/rosindex/issues/113 (i.e. searching capabilities over documentation pages too)?

**Comment by nuclearsandwich** [comment]
> I tried adding an index to the main page. It gets a little bit large, to put it mildly. What do you think about skipping such an index and working towards #113 (i.e. searching capabilities over documentation pages too)?

Unfortunately nothing really replaces an index when you know exactly which page you're looking for in my experience. The GitHub wiki had a big list of article titles that is collapsed by default in the sidebar. It was my primary method of navigating this documentation.

**Comment by hidmic** [comment]
I see. Sidebar index it is then. Thanks for the input.
