### ISSUE TITLE
Broken Link: https://index.ros.org/r/image_transport

### ISSUE THREAD

**Issue by mcsheehan** [ros-infrastructure/rosindex#137]
Goto https://index.ros.org/doc/ros2/Features/ click on image_transport -> broken link

**Comment by sloretz** [comment]
Broken link https://index.ros.org/r/image_transport
What it should be https://index.ros.org/p/image_transport/

**Comment by sloretz** [comment]
@mcsheehan FYI the page with the broken link is in the [ros2/documentation](https://github.com/ros2/ros2_documentation/blob/master/source/Features.rst) repo.
