### ISSUE TITLE
Broken Link: 

### ISSUE THREAD

**Issue by kplmcelligott** [ros-infrastructure/rosindex#148]
should point to: how to install ros1 bridge

**Comment by dirk-thomas** [comment]
Please include more information. It is unclear what link you are referring to.

**Comment by hidmic** [comment]
Ping @kplmcelligott. Otherwise we'll have to close it.

**Comment by dirk-thomas** [comment]
I will go ahead and close this. Please feel free to comment with the necessary information and the ticket can be reopened.
