### ISSUE TITLE
Broken Link: Linux-Development-Setup

### ISSUE THREAD

**Issue by christianrauch** [ros-infrastructure/rosindex#150]
In section https://index.ros.org/doc/ros2/Tutorials/Cross-compilation/#prepare-the-sysroot the word `setup` in
> The standard setup process of ROS2 is run inside an arm docker.

links to the unvailable website https://index.ros.org/doc/ros2/Tutorials/Cross-compilation/Linux-Development-Setup

**Comment by tfoote** [comment]
I opened a ticket for the docs at: https://github.com/ros2/ros2_documentation/pull/147 I'll close this here.
