### ISSUE TITLE
rosindex job is failing to turn over due to failing to add files before commit

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/rosindex#151]
From: http://build.ros.org/job/doc_rosindex/211/consoleText

This looks like the error inside the git invocation.
```
           Writing: /tmp/upload_repository/sitemap.xml
           Writing: /tmp/upload_repository/robots.txt
                    done in 4165.632 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
make: Leaving directory '/tmp/doc_repository'
Traceback (most recent call last):
  File "/usr/local/bin/git_add_files", line 52, in <module>
    run(args)
  File "/usr/local/bin/git_add_files", line 19, in run
    modified_files[file_path]["lines_added"] = int(lines_added)
ValueError: invalid literal for int() with base 10: '-'
HEAD detached at a5b5c82a
Changes not staged for commit:
	modified:   404.html
	modified:   about/design/index.html
```

Same issue on this build: http://build.ros.org/job/doc_rosindex/210/

Unfortunately it seems to be inside of the git_add_files call which is presumably inside the Git Publisher Jenkins plugin. 

https://wiki.jenkins.io/display/JENKINS/Git+Plugin

Which I believe is using the underlying Git Client Plugin
https://wiki.jenkins.io/display/JENKINS/Git+Client+Plugin
However that's java and this looks like a python backtrace.

**Comment by nuclearsandwich** [comment]
If memory serves, Jenkins clones the index.ros.org repository, but our code is responsible for committing changes successfully before the result is pushed back, again by Jenkins.

I'm not sure if we can skip the index with this add but using lower level git commands often makes automation more explicit. Here's an example of using git-commit-tree in a project that synchronizes the _contents_ of two repositories.

https://github.com/gjtorikian/repository-sync/blob/0375da6ff954663cf191a8f923609eb494e28ced/lib/cloner.rb#L240-L241

**Comment by nuclearsandwich** [comment]
I took a look at the git_add_files.py script and I don't have any easy recommendations. It does look like https://github.com/ros-infrastructure/rosindex/blob/d3143f710d21afd3160eafa6a698ba3c28cfcff8/docker/image/git_add_files.py#L19-L20 need to handle more robust input.

**Comment by hidmic** [comment]
I was planning to take a look at this today.
