### ISSUE TITLE
Broken Link: ros1_bridge in section "Install ROS2 packages"

### ISSUE THREAD

**Issue by bergercookie** [ros-infrastructure/rosindex#152]
https://index.ros.org/doc/ros2/Installation/Linux-Install-Debians/

Relevant section:

```
See specific sections below for how to also install the ros1_bridge, TurtleBot packages, or alternative RMW packages.
```

**Comment by tfoote** [comment]
Thanks for the report. This repository is for the infrastructure of the index. 

That content is in the ros2 documentation. https://github.com/ros2/ros2_documentation/blob/master/source/Installation/Linux-Install-Debians.rst Please open a ticket there referencing the line number or even better propose a fix in a PR that would be appreciated.

**Comment by bergercookie** [comment]
Ok, but I got to this page via the "Report broken link" button of the 404 page I ended up at. I suppose the link there needs fixing as well.

**Comment by tfoote** [comment]
Yeah, we understand. That link is site wide and many of the links throughout the index are autogenerated in the infrastructure. However much of the content comes from other repositories which we are indexing. Unfortunately it's hard to communicate exactly where things are coming from.  Especially on the 404 page where we generally don't know where someone came from.
