### ISSUE TITLE
Broken Link: https://index.ros.org/doc/ros2/Tutorials/Ament-CMake-Documentation/Ament_Tutorial.rst

### ISSUE THREAD

**Issue by monicani** [ros-infrastructure/rosindex#154]
Under the ament_cmake User Documentation tutorial, in the Basics section, in the sentence:

"See also the basic ament tutorial."

the link to https://index.ros.org/doc/ros2/Tutorials/Ament-CMake-Documentation/Ament_Tutorial.rst tutorial is broken).

**Comment by MoriKen254** [comment]
I found the same one in the page https://index.ros.org/doc/ros2/Tutorials/Ament-CMake-Documentation/.

**Comment by hidmic** [comment]
This issue actually belongs to https://github.com/ros2/ros2_documentation/, but anyways, the website itself probably led you here in the first place. Thanks for reporting! Also, in the future feel free to provide a fix yourself if interested in doing so.
