### ISSUE TITLE
exec_depends not shown anywhere on dependencies page

### ISSUE THREAD

**Issue by russkel** [ros-infrastructure/rosindex#155]
It seems that exec depends are not interpreted as dependencies and therefore do not show up anywhere on the dependencies page:

https://github.com/uuvsimulator/uuv_simulator/blob/b1837b823b081ab25144b6367a1ce59a8a2ff7c7/uuv_descriptions/package.xml

https://index.ros.org/p/uuv_descriptions/github-uuvsimulator-uuv_simulator/#melodic-deps

**Comment by dirk-thomas** [comment]
Thanks for reporting this. This should be fixed by the referenced fix. The next rebuild of the index page should contain the dependency information for packages using dependencies defined in REP 140.

**Comment by russkel** [comment]
That's looking good now! Thanks @dirk-thomas.
