### ISSUE TITLE
RST to MD conversion broken?

### ISSUE THREAD

**Issue by russkel** [ros-infrastructure/rosindex#162]
When visiting and glancing at the README section:
https://index.ros.org/p/micro_ros_agent/github-micro-ROS-micro-ROS-Agent/#crystal

This error is showing in place of the README: `Could not convert RST to MD: No such file or directory - pandoc`

**Comment by nuclearsandwich** [comment]
Thanks for the report. We're building in a modified environment right now and pandoc was missing. I've added pandoc to the environment and triggered a new build to repair the live site.

**Comment by nuclearsandwich** [comment]
Regenerated documentation has been deployed. Thanks again for reporting the issue.
