### ISSUE TITLE
How to create ros2-gazebo-plugin?

### ISSUE THREAD

**Issue by Pritish9** [ros-infrastructure/rosindex#167]
I am trying to move a robot arm in gazebo. Where the robot arm needs to rotate, any suggestions which plugin to use.

I could not find any so I thought of making my own ros2-gazebo-plugin.

The tutorial ( http://gazebosim.org/tutorials/?tut=ros_plugins ) shows how to make a custom gazebo-plugin with ros. 
Any idea how to make a custom plugin for gazebo for ros2.

**Comment by nuclearsandwich** [comment]
@Pritish9 this issue tracker is for the code which generates http://index.ros.org and isn't a suitable place for your question. I would suggest asking your question on https://answers.gazebosim.org/ or https://answers.ros.org if you're using ROS 2 on the arm.
