### ISSUE TITLE
Sphinx _download directory isn't being preserved.

### ISSUE THREAD

**Issue by nuclearsandwich** [ros-infrastructure/rosindex#170]
ros2_documentation recently added some pdf documents. Sphinx automatically moves these documents into a _downloads/ directory which is not being deployed. I expect that some handling similar to what we do for sphinx images will be needed.

**Comment by gerkey** [comment]
I'm having a look at this.

**Comment by hidmic** [comment]
@gerkey ping me if you need help or you need me to take over.

**Comment by gerkey** [comment]
Thanks @hidmic! @nuclearsandwich gave me enough hints so that I was able to fix it (I think). PR forthcoming.

**Comment by nuclearsandwich** [comment]
The latest deployed code has downloadable PDFs :confetti_ball:
