### ISSUE TITLE
Confusingly incomplete search results

### ISSUE THREAD

**Issue by rotu** [ros-infrastructure/rosindex#178]
I'm noticing that the search doesn't work the way I expect it to, and not how the documentation shows: https://lunrjs.com/guides/searching.html

I was trying to find packages named "*something*_cmake_module", e.g. `python_cmake_module`.

[`*_cmake_module`](https://index.ros.org/search/?term=*_cmake_module) - no results
[`cmake_module`](https://index.ros.org/search/?term=cmake_module) - just `cmake_modules`
[`*_cmake_module*`](https://index.ros.org/search/?term=*_cmake_module*) - shows the correct results

I would expect all these queries to include `python_cmake_module`

**Comment by hidmic** [comment]
Thanks for reporting! Indeed is strange, and basic triage suggests that the problem is in the `lunr.js` index itself. For instance, [`*_cmake_modul`](https://index.ros.org/search/?term=%2A_cmake_modul&section=pkgs) does have the desired outcome.

**Comment by hidmic** [comment]
Someone reported the same issue with `lunr.js` upstream, see https://github.com/olivernn/lunr.js/issues/413.

**Comment by rotu** [comment]
@hidmic great! Thanks for the update

**Comment by hidmic** [comment]
Circling back, I've opened #196. It's not a full solution (it appears we'd have to replace `lunr.js` entirely) but at least it's seemingly consistent.
