### ISSUE TITLE
Better support pages' breadcrumb trail tracking

### ISSUE THREAD

**Issue by hidmic** [ros-infrastructure/rosindex#18]
Breadcrumbs ease site navigation (see below, near the bottom).

![breadcrumb](https://user-images.githubusercontent.com/13500507/45428877-7fb99680-b678-11e8-9e95-e4026e335de5.png)

Current implementation, however, cannot discover them (e.g. based on directory tree structure, which would be quite helpful for #12) but instead relies on them being hardcoded [as front matter data](https://github.com/ros2/rosindex/blob/ros2/contribute/metadata.md) (though severely constrained, as it later [assumes that permalink and title are equal](https://github.com/ros2/rosindex/blob/ros2/_layouts/page.html#L11)), or directly [within HTML templates](https://github.com/ros2/rosindex/blob/ros2/_layouts/package_instance.html#L8). 

Personally, I think that a Jekyll plugin collecting parent page titles as breadcrumbs would do. By _parent_ page I mean a page whose permalink is in the path to the root starting at the given _child_ page permalink, e.g. the page at `/packages/some_package` would include the title of the page at `/packages` as breadcrumb.

What do you think?

**Comment by hidmic** [comment]
Per discussion with @tfoote and @apojomovsky, we can live with this as-is for now.

**Comment by tfoote** [comment]
As a lower bar a possible approach for this would be to just display which repository the page is coming from and have it link back to the top level README for that repo. It wouldn't track a multi layered documentation repository but that would be much more complicated.
