### ISSUE TITLE
Broken Link: 

### ISSUE THREAD

**Issue by cf95** [ros-infrastructure/rosindex#185]
Hi,

i found a broken link, 
directing from page "Migrating launch files from ROS 1 to ROS 2" (https://index.ros.org/doc/ros2/Tutorials/Launch-files-migration-guide/) in section "arg" - "passing an argument via the command line" 
to this page (https://index.ros.org/doc/ros2/Tutorials/Launch-files-migration-guide/Launch-system)

Best Regards
Christian

**Comment by hidmic** [comment]
@cf95 thanks for reporting! Just as an FYI, this isn't quite the appropriate repository to file this issue, https://github.com/ros2/ros2_documentation/ is.

**Comment by cf95** [comment]
Thanks for the info
@hidmic 
I used the "Report Broken Link" button on the page you receive when the link is broken and got redirected here, so maybe you should take a look at this link as well
