### ISSUE TITLE
sphinx-tabs don't work

### ISSUE THREAD

**Issue by maryaB-osr** [ros-infrastructure/rosindex#187]
The `sphinx-tabs` extension is being ignored by ROS index for some reason. 

It's supposed to render like the example [here](https://github.com/djungelorm/sphinx-tabs#grouped-tabs), and it does when building ros2_documentation locally and in the heroku PR deployments.

However, on the main site it ends up [like this](https://index.ros.org/doc/ros2/Tutorials/Configuring-ROS2-Environment/#source-the-setup-files), where the Linux, macOS and Windows examples are all supposed to be tabbed, not listed.

**Comment by tfoote** [comment]
Debugging with @maryaB-osr, we found that the css and js were not being pulled in in the header template on rosindex.

**Comment by hidmic** [comment]
Oops, I forgot about this one! Yeah, that's the problem @tfoote. I have yet to figure out how to pull those in without disrupting `rosindex`, and ideally not coupling the code too much to `sphinx-tabs` implementation details.

**Comment by hidmic** [comment]
@tfoote @maryaB-osr we have a bit of an issue. Even if I was able to somehow copy just enough from what's generated by the `sphinx-tabs` extension into `rosindex` to make this work, it's not even dropping CSS and JS files where it should. The builder we use (i.e. documentation fragments serialized as `json` documents for easy embedding) is not supported by the `sphinx-tabs` extension, see [here](https://github.com/djungelorm/sphinx-tabs/blob/782104f19a401aa68d5a26f9085f5bb0131c2f3b/sphinx_tabs/tabs.py#L301-L305) and [here](https://github.com/djungelorm/sphinx-tabs/blob/782104f19a401aa68d5a26f9085f5bb0131c2f3b/sphinx_tabs/tabs.py#L31-L37).

So we need to add support for the `json` builder upstream (or in a fork) before patching `rosindex`. Good thing is that we could make sure the serialization doesn't get in the way of embedding the generated documentation. Bad thing is that it's likely non trivial to pull this off. Thoughts?

**Comment by tfoote** [comment]
@maryaB-osr We hacked in your local copy to just put the generated content into rosindex manually. Did that work? 

It looks like there some other similar extensions with the same problem of no builder: [content-tabs](https://github.com/ulrobix/sphinxcontrib-contentui/blob/6acb2b6ae29a6b8216a9610e91a938bc8d8f5ea5/sphinxcontrib/contentui.py#L88) 

@maryaB-osr  Maybe there is another alternative that will support the JSON builder?

**Comment by maryaB-osr** [comment]
@tfoote No, it didn't. After I pulled in the new tutorials,  `make build` works but always throws the extension error `could not import sphinx-tabs`. When I serve the site, all the sections work (About, Index, Contribute, Stats) except the "Doc" section. Trying to access `/doc/ros2` gives a 404. So I can't even reach the tutorials to see if the tabs are working, even if I manually add the tutorial's path to the URL.

**Comment by hidmic** [comment]
@tfoote @maryaB-osr I'm on this. I think I'm close but I've had to fork `sphinx-tabs` :/

**Comment by hidmic** [comment]
Alright, tabs are up at https://index.ros.org/doc/ros2/
