### ISSUE TITLE
Index doesn't generate for pages in nested directories

### ISSUE THREAD

**Issue by maryaB-osr** [ros-infrastructure/rosindex#189]
Just the title, mentioned here: https://github.com/ros2/ros2_documentation/pull/409#issue-339637974

**Comment by maryaB-osr** [comment]
Few more of the pages where the index doesn't generate; it's not just nested directories

https://index.ros.org/doc/ros2/Governance/
https://index.ros.org/doc/ros2/Marketing/
https://index.ros.org/doc/ros2/Troubleshooting/

**Comment by hidmic** [comment]
Should be fixed by #195 and https://github.com/ros2/ros2_documentation/pull/452.
