### ISSUE TITLE
Change the order of the navigation links

### ISSUE THREAD

**Issue by maryaB-osr** [ros-infrastructure/rosindex#193]
Instead of the automatic alphabetical order for the side bar index navigation table, the pages should be in their logical order:

    Installation
    Roadmap
    Distributions
    Concepts
    Features Status
    Tutorials
    Troubleshooting
    Contributing
    Project Governance
    Marketing Materials
    Related Projects
    Contact us
    About this documentation

And the same should go for the second-level contents (i.e. tutorials should be ordered based on their order listed on the [tutorials page](https://github.com/ros2/ros2_documentation/blob/master/source/Tutorials.rst))

Anything lower than second-level (like `Tutorials/Actions/Creating an action`)shouldn't be visible from the side bar (it's too much info plus it will be harder to maintain since we're manually ordering it now).

Not sure if this issue should be here or over on [ros2/ros2_documentation](https://github.com/ros2/ros2_documentation) since the order definition should be in that repo (so it can be updated in a single PR with documentation changes)

If for some reason a new top- or second-level page is added without being manually added to the order definition, there should be some mechanism for it to be automatically added to the sidebar anyway, maybe just at the end of the list.

**Comment by hidmic** [comment]
Should be addressed by https://github.com/ros2/ros2_documentation/pull/452. I had forgotten about `rosindex.yml`. @maryaB-osr you may change it again in the future to further restrict what gets indexed and in what ordered.
