### ISSUE TITLE
tags: Distinguish tags of specific package from tags of other packages in the repo

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-infrastructure/rosindex#198]
This is a repost of https://github.com/rosindex/rosindex/issues/146 (which references https://github.com/rosindex/rosindex/issues/144).

From https://github.com/rosindex/rosindex/issues/144:

> Package tags seem to be aggregated across all pkgs in a repository, and that set is then displayed for all pkgs in the repository. See [fanuc](https://index.ros.org/p/fanuc/github-ros-industrial-fanuc/) (metapackage) and [fanuc_driver](https://index.ros.org/p/fanuc_driver/github-ros-industrial-fanuc/) fi. Is this intended behaviour?

**Comment by max-krichenbauer** [comment]
If the intended behavior could be confirmed to me by a maintainer, I could work on providing a PR for this.

**Comment by gavanderhoorn** [comment]
At least @jbohren agreed that each package should only show the tags it `export`s in its package manifest.

**Comment by tfoote** [comment]
Yeah, I'd agree that tags should be limited to the package exporting them. The repository level page can show the aggregation of them, but it doesn't make sense to show tags for peer packages. The fact that they're side by side in a repository is just an artifact of their hosting and should not be relevant to the package. (If the package is moved it's content doesn't change.)

**Comment by max-krichenbauer** [comment]
Created https://github.com/ros-infrastructure/rosindex/pull/202 with a fix.
Let's continue the conversation there and close this issue if acceptable.

**Comment by max-krichenbauer** [comment]
I guess this issue can be closed now, since the PR implementing it has been merged.

**Comment by gavanderhoorn** [comment]
Yes, it can be closed.

Thanks for the work @max-krichenbauer.
