### ISSUE TITLE
Include readme's filename in title

### ISSUE THREAD

**Issue by apojomovsky** [ros-infrastructure/rosindex#22]
On top of what was done in #17, we might want to display the actual name of each of the readme files at the beginning of each block.
As an example, for the image below, we might want to display the name of the second readme block as `RCL_README` instead of just `README`:

![image](https://user-images.githubusercontent.com/5348967/45437043-881acd00-b68a-11e8-9ce6-a3fd02eddf37.png)

Thoughts on this @tfoote @hidmic ?

**Comment by tfoote** [comment]
Yes otherwise it's not clear where they came from.

While we're at it would it be possible to make the title also link to the source? Maybe only if it's in a known hosting site like github where the url format can be patterned?

**Comment by apojomovsky** [comment]
Yes, that makes perfect sense. I'm renaming this question as a issue then.
FYI @hidmic
