### ISSUE TITLE
Broken Link: https://index.ros.org/doc/ros2/Tutorials/Defining-custom-interfaces-(msg-srv)/

### ISSUE THREAD

**Issue by mightestDuck** [ros-infrastructure/rosindex#224]
first result in google for "ros2 service definition using custom message types"

**Comment by tfoote** [comment]
Please clarify what page you're finding a broken link on. 

The first results in google for that phrase gives me https://index.ros.org/doc/ros2/Tutorials/Rosidl-Tutorial/

**Comment by mightestDuck** [comment]
It's given in the title of the issue...

[https://index.ros.org/doc/ros2/Tutorials/Defining-custom-interfaces-(msg-srv)/](https://index.ros.org/doc/ros2/Tutorials/Defining-custom-interfaces-(msg-srv)/)

**Comment by tfoote** [comment]
I don't see a tutorial by that name or any similar name: https://github.com/ros2/ros2_documentation/tree/master/source/Tutorials The content is in that other repo please file your ticket there. If you can point to the page with the broken link as well as the target of the broken link it will make it much easier to fix.
