### ISSUE TITLE
Broken link to submit new repo instance

### ISSUE THREAD

**Issue by rotu** [ros-infrastructure/rosindex#226]
The button to submit a new repo instance is broken and takes me to a 404 page on github

https://index.ros.org/repos/rmw_cyclonedds/
broken link: https://github.com/rosindex/rosforks/edit/source/repos/rmw_cyclonedds.md

**Comment by tfoote** [comment]
We aren't currently supporting manually adding new instances, everything should go through the rosdistro. Until we reenable that we should probably remove that button.
