### ISSUE TITLE
Old link to atolab cyclonedds repo

### ISSUE THREAD

**Issue by rotu** [ros-infrastructure/rosindex#227]
This index page lists two repos for rmw_cyclonedds
https://index.ros.org/repos/rmw_cyclonedds/

The atolab one is obsolete and redirects to the other one. Please clean up the source data or direct me to where I can submit a PR.

**Comment by tfoote** [comment]
This is generated from the rosdistro content: which I see you've already updated. https://github.com/ros/rosdistro/pull/24380
