### ISSUE TITLE
many packages missing from rosindex

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/rosindex#228]
https://index.ros.org/p/ros_base/github-ros2-variants/#dashing

![Screenshot from 2020-04-07 13-56-30](https://user-images.githubusercontent.com/447804/78719379-b26d5480-78d8-11ea-9af0-39520f480e37.png)

https://index.ros.org/p/tf2/

![Screenshot from 2020-04-07 14-05-20](https://user-images.githubusercontent.com/447804/78719488-d9c42180-78d8-11ea-9987-bc906f762c8d.png)

There was a precipitous drop in times a little while ago:

![Screenshot from 2020-04-07 14-06-28](https://user-images.githubusercontent.com/447804/78719592-06783900-78d9-11ea-9c07-fe47b16a5188.png)

In the recent logs I'm seeing a lot of "Bad URI" errors such as here: http://build.ros.org/job/doc_rosindex/443/consoleText

```
[1;31mERROR (github-ros-planning-geometric_shapes): Could not fetch source repo: Could not reach git repository at uri: https://github.com/ros-planning/geometric_shapes.git: Bad URI: https://github.com/ros-planning/geometric_shapes.git[0m
Updating repo / instance geometry_angles_utils / github-ros-angles from uri: https://github.com/ros/angles.git
[1;31mERROR: Bad URI: https://github.com/ros/geometry.git[0m
[1;31mERROR: Could not reach git repository at uri: https://github.com/ros/geometry.git: Bad URI: https://github.com/ros/geometry.git[0m
[1;33mFailed to communicate with source repo after 3 attempt(s)[0m
[1;31mERROR (github-ros-geometry): Could not fetch source repo: Could not reach git repository at uri: https://github.com/ros/geometry.git: Bad URI: https://github.com/ros/geometry.git[0m
Updating repo / instance geometry_tutorials / github-ros-geometry_tutorials from uri: https://github.com/ros/geometry_tutorials
[1;31mERROR: Bad URI: https://github.com/ros/geometry2.git[0m
[1;31mERROR: Could not reach git repository at uri: https://github.com/ros/geometry2.git: Bad URI: https://github.com/ros/geometry2.git[0m
[1;33mFailed to communicate with source repo after 1 attempt(s)[0m
[1;31mERROR: Bad URI: https://github.com/ros/angles.git[0m
[1;31mERROR: Could not reach git repository at uri: https://github.com/ros/angles.git: Bad URI: https://github.com/ros/angles.git[0m
[1;33mFailed to communicate with source repo after 1 attempt(s)[0m
[1;31mERROR: Bad URI: https://github.com/ros/geometry2.git[0m
```

I'm wondering if this is a rate limiting thing from github.

**Comment by tfoote** [comment]
Debug info in #229 229

**Comment by tfoote** [comment]
This is confirmed to be rate limiting witha 429 http code

http://build.ros.org/job/doc_rosindex/446/console
> https://github.com/baalexander/rospy_message_converter.git: Code 429 bad URI:

**Comment by rotu** [comment]
I just realized this and was very confused. Any progress on getting it fixed? Could you please throw up a status message on https://status.ros.org/ and maybe a banner on index.ros.org?
