### ISSUE TITLE
Move containerization bits into rosindex

### ISSUE THREAD

**Issue by hidmic** [ros-infrastructure/rosindex#23]
In our quest to get rid of submodules, we'd like to move all rosindex containerization specific bits, currently living at [ros-infrastructure/rosindex_containers](https://github.com/ros-infrastructure/rosindex_containers), into rosindex repo itself. Preferably in an appropriately named subdirectory.

**Comment by hidmic** [comment]
@tfoote @apojomovsky I was thinking that it'd be nice to have the Dockerfile using the site's Gemfile and avoid listing dependencies twice. What do you think?

**Comment by tfoote** [comment]
> @tfoote @apojomovsky I was thinking that it'd be nice to have the Dockerfile using the site's Gemfile and avoid listing dependencies twice. What do you think?

That would be great.
