### ISSUE TITLE
Doppelganger rosindex

### ISSUE THREAD

**Issue by rotu** [ros-infrastructure/rosindex#230]
The first google result for "rosindex" brings me to http://rosindex.github.io/, which is visually similar to https://index.ros.org/ but unmaintained. The only clue that something is amiss is easy to miss text "generated on 2016-07-04".

It would be nice to close the old site and redirect here.

**Comment by hidmic** [comment]
@tfoote can we pull the plug for the old site?

**Comment by tfoote** [comment]
With @jbohren 's assistance we've taken the old site offline.
