### ISSUE TITLE
Broken Link:  https://index.ros.org/doc/ros2/Tutorials/Python-Programming/

### ISSUE THREAD

**Issue by eszter007** [ros-infrastructure/rosindex#235]

**Comment by tfoote** [comment]
That url doesn't exist so presumably it's the target. However to fix the problem we need at least a link to the source url. Based on the url, my guess is that it comes from one of the pages in ros2_documentation where the documentation pages for index.ros.org/doc is hosted: https://github.com/ros2/ros2_documentation
