### ISSUE TITLE
Broken Link: 

### ISSUE THREAD

**Issue by albertleng** [ros-infrastructure/rosindex#238]
I am redirected to https://index.ros.org/doc/ros2/Tutorials/Creating-A-ROS2-Package/ from https://github.com/ros2/ros2cli/pull/428 but it's a broken link.

**Comment by clalancette** [comment]
@maryaB-osr Should this redirect work?

**Comment by maryaB-osr** [comment]
We have https://index.ros.org/doc/ros2/Tutorials/Creating-Your-First-ROS2-Package/  and https://index.ros.org/doc/ros2/Tutorials/Developing-a-ROS-2-Package/ but that's it. I'm not sure if /Creating-A-ROS2-Package was ever a page. I know ros2/ros2cli#428 was about "Creating your first ROS 2 package", maybe Tully handwrote the url from memory and mixed it up a bit. Should I add a redirect to the page even though this is likely the only place it's mixed up, or should we just edit that issue description so no one else ends up following that broken link?

**Comment by clalancette** [comment]
It does look like that used to be a page: https://github.com/ros2/ros2_documentation/commit/321ae8ccd08572e90aa6069bfbd2c8dce619f1b6 is the commit that renamed it.

In general, I don't think we need to go back and edit *every* outdated link.  It would be nice (though not totally required) to link from the ones that used to work, though.

**Comment by tfoote** [comment]
Closing this as we're migrating again and double forwarding doens't make sense. Also this was likely lost because the content and redirects are in https://github.com/ros2/ros2_documentation/
