### ISSUE TITLE
[question] how quickly does rosindex get updated?

### ISSUE THREAD

**Issue by flynneva** [ros-infrastructure/rosindex#241]
I've got two packages that were just recently (5 days ago) merged into rosdistro and one of them hasn't been updated yet on rosindex.

is there a timeline/schedule for when index.ros.org will be updated?

**Comment by cottsay** [comment]
There was an infrastructure issue with the rosindex update job that I was unaware of. I've resolved the issue, and the job is running now. Hopefully we'll have an up-to-date index in a couple of hours.

Thanks for bringing this to our attention.
