### ISSUE TITLE
Broken Link: ezrassor-controller-server leo-description

### ISSUE THREAD

**Issue by CostaRolls** [ros-infrastructure/rosindex#245]
Hi,

the SRC_URI of the recipes point to a non-existent repository since these recipes were renamed! If I try to build a target image with the packagegroup packagegroup-ros-world for ROS1 melodic in the dunfell branch of the YP it crashes during the build.

Best regards,

Daniel Costa Behrens

**Comment by tfoote** [comment]
This content comes from the upstream package or https://github.com/ros/rosdistro please file a ticket with one of them.
