### ISSUE TITLE
Setup documentation repositories

### ISSUE THREAD

**Issue by hidmic** [ros-infrastructure/rosindex#25]
Once support for non-package specific documentation repositories is in (#13), we need to setup real repositories with real content, that we can readily get from wiki.ros.org.

**Comment by hidmic** [comment]
@tfoote would it make sense to pull content from [ROS2 wiki](https://github.com/ros2/ros2/wiki) instead/in addition? Also, I think it'd make sense to create such repos within ros/ros2 Github organizations.

**Comment by dirk-thomas** [comment]
Yes, all the content from the ROS 2 wiki should be migrated at some point.

**Comment by hidmic** [comment]
@tfoote would you setup a ros/ros2 repo for this? I think I don't have enough permissions to do so. I'll collect documentation in the meantime.

**Comment by tfoote** [comment]
Sure can you transfer the current repo to me? And then I can push it to the ros2 org. Using the transfer mechanisms github's redirects will keep everything working.

**Comment by hidmic** [comment]
Ready @tfoote. Pushed entire ROS2 wiki. May need some cleanup too.

**Comment by tfoote** [comment]
Content is now here: https://github.com/ros2/ros2_documentation
