### ISSUE TITLE
Page not shows content

### ISSUE THREAD

**Issue by aldajo92** [ros-infrastructure/rosindex#255]
Looks like there was an error in the content because the page shows empty labels for titles and sections.
<img width="1345" alt="Screen Shot 2021-03-01 at 1 33 05 PM" src="https://user-images.githubusercontent.com/5512956/109542131-aa8b4580-7a92-11eb-838c-597e7ef2041a.png">

**Comment by aldajo92** [comment]
Sorry, checking in the issues, I found that the new ROS2 home page is https://docs.ros.org/en/foxy/index.html

**Comment by clalancette** [comment]
There is actually a problem here, in that there should be redirects from the old content to the new content.  I'm not sure why that didn't work, I'm debugging it now.

**Comment by clalancette** [comment]
I have a temporary fix in place (so the site should be back up), and a more permanent fix is coming in https://github.com/ros2/ros2_documentation/pull/1158
