### ISSUE TITLE
Broken Link: https://index.ros.org/doc/ros2/ROS-2-Client-Libraries/

### ISSUE THREAD

**Issue by supreethk6** [ros-infrastructure/rosindex#280]
Got redirected from ROS Construct Sim page to this link where-in it is broken.
Description of the link =>  other client libraries have been developed by the ROS community. You can check out the following article for more details: https://index.ros.org/doc/ros2/ROS-2-Client-Libraries/

**Comment by clalancette** [comment]
Thanks for the report.  https://github.com/ros2/ros2_documentation/pull/2378 should fix the problem.

**Comment by tfoote** [comment]
This works with the fix linked
