### ISSUE TITLE
Broken Link: ros2 control demos foxy related packages

### ISSUE THREAD

**Issue by enriLoniterp** [ros-infrastructure/rosindex#286]
I was at [ros2_control_demo](https://github.com/ros-controls/ros2_control_demos) and looking for ros2 control demos foxy related packages. Not working

**Comment by clalancette** [comment]
Can you please be more specific on what is not working?  An exact URL or at least a pointer to what in `ros2_control_demo` is not working would be helpful.

**Comment by enriLoniterp** [comment]
![foxy error](https://user-images.githubusercontent.com/43698855/183417200-8253fa5b-e7f2-404e-a654-fc1f81cb529c.PNG)
![link](https://user-images.githubusercontent.com/43698855/183417192-5743a997-310b-42a2-9729-cb3f524dc4e7.PNG)

I'm in the first image on git hub ros2 control demos [here](https://github.com/ros-controls/ros2_control_demos), then i click to related packages and got that issue.

**Comment by clalancette** [comment]
Thanks, that is helpful.

In this case, the reason that the link is broken is that this particular package has not been released into any of the ROS 2 distributions.  Please open up an issue on https://github.com/ros-controls/ros2_control_demos asking the maintainers to either release into the ROS 2 distributions, or to remove the links.
