### ISSUE TITLE
Broken Link: rosbag2

### ISSUE THREAD

**Issue by ghost** [ros-infrastructure/rosindex#289]
https://index.ros.org/doc/ros2/API/rosbag2_py/
This link to the rosbag2 API is broken.
For your general knowledge.

**Comment by tfoote** [comment]
That link doesn't look valid you can find out more about rosbag2_py here: https://index.ros.org/p/rosbag2_py/ The generated API docs for python are being worked on at the moment. Hopefully they'll be available soon. 

https://github.com/ros-infrastructure/rosdoc2/pull/28
https://github.com/ros-infrastructure/rosdoc2/pull/49
