### ISSUE TITLE
Broken Link: 

### ISSUE THREAD

**Issue by TwinkleGoyal08** [ros-infrastructure/rosindex#290]
is foxy version is still being maintained, i m just starting out with ros2 control, if possible suggest some other version where i can practice without much errors, also the link provided in documentation for downloading ros control package also doesn't work

**Comment by clalancette** [comment]
Please open questions like this on https://answers.ros.org, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.
