### ISSUE TITLE
Broken Link: 

### ISSUE THREAD

**Issue by Geylian** [ros-infrastructure/rosindex#303]
The following link on the [robotino_node documentation](http://wiki.ros.org/robotino_node)  is no longer working:
[https://index.ros.org/p/robotino_node](https://index.ros.org/p/robotino_node)

![image](https://github.com/ros-infrastructure/rosindex/assets/43343595/70d38d1f-febe-4d85-93a5-4d972c5a03f7)

**Comment by tfoote** [comment]
The last robotino version of the package indexed appears to be in Electric: https://github.com/search?q=repo%3Aros%2Frosdistro+robotino&type=code most of the content on wiki.ros.org has been removed and Index.ros.org doesn't index anything before Kinetic which is already significantly EOL.
