### ISSUE TITLE
Broken Link: 

### ISSUE THREAD

**Issue by bus0v** [ros-infrastructure/rosindex#313]
[See robot_monitor on index.ros.org for more info including aything ROS 2 related.](https://index.ros.org/p/robot_monitor) on this page http://wiki.ros.org/robot_monitor is a broken link

**Comment by tfoote** [comment]
Thanks for reporting this. However robot_monitor is missing from the new index because it was last released in groovy and the source code is no longer available. The groovy release was over a decade ago: https://github.com/ros/rosdistro/milestone/2
