### ISSUE TITLE
Rosdep does not recognise natively packaged vcstool as a valid system dependency

### ISSUE THREAD

**Issue by DaviAntonio** [ros-infrastructure/rosindex#316]
Due to the [current settings](https://index.ros.org/d/python3-vcstool/) Ubuntu and Debian are forced to download `vcstool` from the ROS Debian package repository, where it is available under the name `python3-vcstool`. Alpine, OSX, Macports and Gentoo are able to use their native `vcstool` package, though.

I believe the index should allow the natively packaged `vcstool` to be installed as a system dependency on the supported versions of Ubuntu and Debian. According to their package indexes, Ubuntu has `vcstool` 0.3 available since [Kinetic Kudu/22.10](https://launchpad.net/ubuntu/+source/ros-vcstool) and Debian since the current stable, [bookworm/12](https://tracker.debian.org/pkg/ros-vcstool).

**Comment by tfoote** [comment]
Following our UpstreamPackages policy http://wiki.ros.org/UpstreamPackages we explicitly recommend against mixing upstream packages with our installation candidates. 

Note that this is the wrong place to ticket something like that. This repo is for rendering the index, not about the content of the index which would be in https://github.com/ros/rosdistro
