### ISSUE TITLE
CI Status is not being detected correctly anymore

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/rosindex#332]
From my testing everything is reporting: 

'No Continuous Integration'

For example: https://index.ros.org/p/roscpp/ which definitely has CI enabled.

**Comment by tfoote** [comment]
Fixed in #355

FYI @rkent Github will cross link if you put the issue ID in the body but not in the Title. And if you say `Fixes #XXX` in a pull request body github will auto close the issue when the PR is merged.

**Comment by rkent** [comment]
Thanks for the feedback!
