### ISSUE TITLE
Broken Link: https://index.ros.org/doc/ros2/Tutorials/Releasing-a-ROS-2-package-with-bloom/

### ISSUE THREAD

**Issue by fabawi** [ros-infrastructure/rosindex#338]
The bloom instruction link for ROS 2 on [https://wiki.ros.org/bloom/Tutorials/FirstTimeRelease](https://wiki.ros.org/bloom/Tutorials/FirstTimeRelease) in the note under section **2.Preparing the Upstream Repository**

**Comment by tfoote** [comment]
Thanks for the report, I have fixed the reference. https://wiki.ros.org/action/diff/bloom/Tutorials/PrepareUpstream?action=diff&rev1=11&rev2=12
