### ISSUE TITLE
Broken Link: 

### ISSUE THREAD

**Issue by harshmangalam** [ros-infrastructure/rosindex#345]
https://index.ros.org/doc/ros2/Contributing/Developer-Guide/

**Comment by clalancette** [comment]
So there are 2 things here:

1.  That link is very outdated, and we haven't depended on it for several years.  Can you let us know how you got to that link?
2.  Regardless of 1, there should be a redirect from that link to our new documentation.  Somehow that must not be working properly, I'll see if I can track it down.

**Comment by harshmangalam** [comment]
I was exploring `Installing and configuring ROS Environment` docs and there i got broken link for ROS 2 docs
http://wiki.ros.org/ROS/Tutorials/InstallingandConfiguringROSEnvironment

<img width="1405" alt="Screenshot 2024-01-30 at 9 23 35 PM" src="https://github.com/ros-infrastructure/rosindex/assets/57381638/45a65b4e-56bd-49a8-8796-abb9f1b5a7a8">

**Comment by clalancette** [comment]
Thanks for that.  We ended up deciding not to keep the redirects (they were already there for 3 years), so I've now updated the wiki page to point to the correct documentation.  Thank for the report.
