### ISSUE TITLE
Broken Link: https://index.ros.org/doc/ros2/Tutorials/Configuring-ROS2-Environment/#source-the-setup-files

### ISSUE THREAD

**Issue by deepak-anzo** [ros-infrastructure/rosindex#349]
The link for the setup is not working. Please look into this.

https://index.ros.org/doc/ros2/Tutorials/Configuring-ROS2-Environment/#source-the-setup-files

**Comment by clalancette** [comment]
> The link for the setup is not working. Please look into this.

We recently removed these redirects that were there for many years.  The canonical place for documentation is https://docs.ros.org .

Can you please let us know where you followed that link from?  Maybe we can update that location.

**Comment by tfoote** [comment]
Closing due to no follow up. We can't fix the link without knowing where it's coming from.
