### ISSUE TITLE
Broken Link: Found on micro ros website in the overview section on framework

### ISSUE THREAD

**Issue by HrishikeshMRao** [ros-infrastructure/rosindex#350]
This link was supposed to be pointed to ros2 framework but it seems like it is broken so thought of reporting this issue.
[Micro-ros](https://micro.ros.org/docs/overview/features/)
press the ros2 architecture hypertext. within the above link under the heading layered module architecture.

Thankyou

**Comment by clalancette** [comment]
Thanks for the report.  The link in that documentation is old and outdated, so I've opened up https://github.com/micro-ROS/micro-ROS.github.io/pull/414 to fix it.

I'm going to close this out, since there is nothing on rosindex to fix.
