### ISSUE TITLE
Broken Link: https://index.ros.org/doc/ros2/Tutorials/Configuring-ROS2-Environment/#source-the-setup-files

### ISSUE THREAD

**Issue by ashwani-anzo** [ros-infrastructure/rosindex#351]
[SOURCE THE ROS 2 SETUP FILE](https://index.ros.org/doc/ros2/Tutorials/Configuring-ROS2-Environment/#source-the-setup-files) is not working

**Comment by clalancette** [comment]
Can you please let us know where you followed that link from?

**Comment by tfoote** [comment]
Closing due to no follow up. We can't fix the link without knowing where it's coming from.
