### ISSUE TITLE
How can I get the value of a particular cell?

### ISSUE THREAD

**Issue by Ion1811** [ros-infrastructure/rosindex#360]
I'm trying to get the heigth value of a cell with the next function, but i'm always getting the whole array on screen.
My code is this:
index_x = int((x - self.grid_map.info.pose.position.x) / self.grid_map.info.resolution)
index_y = int((y - self.grid_map.info.pose.position.x) / self.grid_map.info.resolution)
if 0 <= index_x < self.grid_map.info.length_x and 0 <= index_y < self.grid_map.info.length_y:
height_index = int(index_y * self.grid_map.info.length_x + index_x)
if len(self.grid_map.data) > 0:
height = self.grid_map.data[height_index]
return height

**Comment by clalancette** [comment]
Please open questions like this on https://robotics.stackexchange.com/questions/tagged/ros, which is our central Question and Answer site.  You'll get a better answer there, and it will be searchable for the future.

Make sure to include a lot of information on what platform you are using, which ROS distribution you are using, and the exact steps you took.
