### ISSUE TITLE
Replace 404 Issue reporting link with Issue Form

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/rosindex#362]
The new Issue Form is a good way to get reports with better syntax. 

We've had a lot of empty broken link issues recently which are just noise for us and not satisfying for the people taking the effort to file them. 

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms

**Comment by gabrielhsdev** [comment]
Hello @tfoote 
I noticed this open issue and I'm interested in tackling it. Would it be possible for me to take ownership of this and work on a solution? I believe I can contribute effectively to resolving it.

Looking forward to your response! Thanks

**Comment by tfoote** [comment]
It would be great if you wanted to take this one. I'll be happy to review PRs to change this. In addition to making the form you'd want the link to point to it. 

The link is here in the code: https://github.com/ros-infrastructure/rosindex/blob/ros2/404.html I've linked the above layout. 

Examples of the problematic pull requests can be found by searching broken link is:closed: https://github.com/ros-infrastructure/rosindex/issues?q=is%3Aissue+is%3Aclosed+broken+link

In the best case you could find a way to automatically detect what url the 404 was attempting to go to so the form only has to collect the source location from the user. 

In the form I'd ask that you get both the linking page url as well as the link text for easier finding to try to find the link if the page is long.

**Comment by gabrielhsdev** [comment]
Hi @tfoote 
I will start working on this one then, can I be assigned to the issue? 
Thanks

**Comment by gabrielhsdev** [comment]
Hi @tfoote 

I've been considering the structure of the form for reporting broken links. Here's what I've could come up with:

## Form Structure

I propose the following fields for the form:

- **Title:** The default title could be "Broken Link," aligning with the existing issue titles. This field would be automatically filled.
- **User Email:** This allows us to easily get in touch with users regarding their reported issues.
- **Link for the 404 Error Page:** This would automatically capture the URL of the page that was not found.
- **Referrer Page:** This field would automatically capture the URL of the page that led us to the 404 Error.
- **Quick Description of the Error:** Users can optionally provide additional context or details here. We could set a default description to ensure this field is not left blank.

Looking forward to your thoughts on this approach. 
Thanks

**Comment by tfoote** [comment]
That looks good, though I would drop the email submission. They can be contacted via the issue on GitHub which will be reported by their user. So any comment back on the issue will give them a notification. Using JavaScript to get the 404 URL automatically would be great. You might add that to the generated title too.

**Comment by gabrielhsdev** [comment]
Hello @tfoote,

I encountered some initial hiccups with Docker on my machine, but it looks like everything is sorted out now, and I'm ready to kick off my development work. I'll be working on addressing this issue and plan to submit a pull request within the next few days.

Thanks for your patience!

**Comment by gabrielhsdev** [comment]
Hi @tfoote 

I've submitted a pull request addressing the issue you mentioned. Could you kindly review it when you have a moment?

Edit: Fixed the link, new PR
Pull Request Link: [PR #365](https://github.com/ros-infrastructure/rosindex/pull/365)

Thank you!

**Comment by tfoote** [comment]
Thanks for working on this @gabrielhsdev I'm going to close this as resolved by the PR.
