### ISSUE TITLE
Broken Link:https://index.ros.org/p/ctx2140

### ISSUE THREAD

**Issue by Toshith22** [ros-infrastructure/rosindex#370]
### 404 Page URL

https://index.ros.org/p/ctx2140

### Referrer URL

http://wiki.ros.org/ctx2140

### Description

I clicked on "See ctx2140 on index.ros.org for more info including aything ROS 2 related" present on the referrer URL.

**Comment by CursedRock17** [comment]
What brought you over to ctx2140 in the first place? I personally have never seen that before, especially related to any ROS context.

**Comment by tfoote** [comment]
Removed that wiki page which had no content
