### ISSUE TITLE
Broken Link:https://index.ros.org/doc/ros2/Installation

### ISSUE THREAD

**Issue by dzhonapp** [ros-infrastructure/rosindex#372]
### 404 Page URL

https://index.ros.org/doc/ros2/Installation

### Referrer URL

https://classic.gazebosim.org/tutorials?tut=ros2_installing

### Description

I was trying to get to this link but looks like it is broken. Thanks.

**Comment by CursedRock17** [comment]
A couple of things, I don't think the link is meant to send you over to `rosindex`, I think that was a mistake on the gazebo documentation side. Apart from the fact that gazebo-classic is I believe, about to go EOL, the version of ROS 2 that it works with is already EOL (End of life) - here's the link that you would've needed to follow though: https://docs.ros.org/en/foxy/Installation.html. Though, personally I would start with this: https://gazebosim.org/docs

**Comment by clalancette** [comment]
This was fixed in https://github.com/osrf/gazebo_tutorials/pull/179, but I guess it hasn't been deployed yet since it is still pointing to the older documentation.  @azeey do you know if a deploy was done?

**Comment by CursedRock17** [comment]
It seems as though the link to the installation process is working now, we could probably close this, right?

**Comment by azeey** [comment]
Yes, the changes have been deployed, so we can close this.
