### ISSUE TITLE
Broken Link:https://index.ros.org/doc/ros2/Concepts/About-ROS-Interfaces/

### ISSUE THREAD

**Issue by ldbrouwer** [ros-infrastructure/rosindex#376]
### 404 Page URL

https://index.ros.org/doc/ros2/Concepts/About-ROS-Interfaces/

### Referrer URL

https://index.ros.org/doc/ros2/Concepts/About-ROS-Interfaces/

### Description

On the iRobot Create Msgs Page
iRobot® Create® Platform interfaces
ROS 2 action, message, and service definitions used by the iRobot® Create® Platform.

For more information about ROS 2 interfaces, see [index.ros2.org](https://index.ros.org/doc/ros2/Concepts/About-ROS-Interfaces/)

**Comment by CursedRock17** [comment]
It seems like they meant to link to the current docs page, if you're looking to learn about ROS 2 interfaces I would recommend you use the starting tutorials: 
- https://docs.ros.org/en/rolling/Tutorials/Beginner-CLI-Tools/Understanding-ROS2-Topics/Understanding-ROS2-Topics.html
-  https://docs.ros.org/en/rolling/Tutorials/Beginner-CLI-Tools/Understanding-ROS2-Services/Understanding-ROS2-Services.html
-  https://docs.ros.org/en/rolling/Tutorials/Beginner-CLI-Tools/Understanding-ROS2-Actions/Understanding-ROS2-Actions.html

On that note, I'm going to open an issue on the [GitHub Repo](https://github.com/iRobotEducation/irobot_create_msgs/issues) to replace it with a simple overview: https://docs.ros.org/en/rolling/How-To-Guides/Topics-Services-Actions.html

Though, the repository hasn't been updated in two years, so it may not be fixed for a while

**Comment by ldbrouwer** [comment]
Thanks Lucas – 

 

                I found what I needed. Great info!

Just wanted to report the broken link

 

Lonnie
