### ISSUE TITLE
Broken Link:https://index.ros.org/doc/ros2/Troubleshooting/Installation-Troubleshooting/#import-failing-without-library-present-on-the-system

### ISSUE THREAD

**Issue by kjkthoth** [ros-infrastructure/rosindex#379]
### 404 Page URL

https://index.ros.org/doc/ros2/Troubleshooting/Installation-Troubleshooting/#import-failing-without-library-present-on-the-system

### Referrer URL

IDK. This happened at isaac saim run extension tests

### Description

While I was about to see the solution about connection error between Isaac Sim and ROS2 foxy.

**Comment by tfoote** [comment]
Please ticket this with Isaac Sim, they need to update the link that's embedded internally. We can't resolve it from here.
