### ISSUE TITLE
Broken Link:https://index.ros.org/doc/ros2/Tutorials/Colcon-Tutorial/

### ISSUE THREAD

**Issue by ptbw** [ros-infrastructure/rosindex#380]
### 404 Page URL

https://index.ros.org/doc/ros2/Tutorials/Colcon-Tutorial/

### Referrer URL

https://answers.ros.org/question/336710/why-isnt-catkin_make-working/

### Description

Link to tutorial on colcon

**Comment by CursedRock17** [comment]
Since the link was commented on the old site answer.ros.org it probably won't let me update it, but you're looking for the updated `Colcon` tutorial, seen on the rolling branch here:
https://docs.ros.org/en/rolling/Tutorials/Beginner-Client-Libraries/Colcon-Tutorial.html

**Comment by tfoote** [comment]
Yeah, that's been archived so we can't fix it. There may be an equivalent of the question on robotics.stackexchange.com that could be fixed, but a cursory search didn't find it. Closing this issue w/o a concrete task to follow up on.
