### ISSUE TITLE
Broken Link:https://index.ros.org/doc/ros2/Installation/Dashing/Linux-Install-Debians

### ISSUE THREAD

**Issue by EnricoMendez** [ros-infrastructure/rosindex#381]
### 404 Page URL

https://index.ros.org/doc/ros2/Installation/Dashing/Linux-Install-Debians

### Referrer URL

https://github.com/intel/ros2_grasp_library/blob/master/grasp_tutorials/doc/grasp_ros2/tutorials_1_grasp_ros2_with_camera.md

**Comment by CursedRock17** [comment]
Odds are it was trying to lead users to the installation process for linux on the `dashing` distribution, `dashing` was sent to end of life as of May 2021, so here's the rolling branch and the most recent distribution (Jazzy), respectively:
https://docs.ros.org/en/rolling/Installation/Ubuntu-Install-Debians.html
https://docs.ros.org/en/jazzy/Installation/Ubuntu-Install-Debians.html

As for updating the link, the repository was archived April 8th, 2024, so it might not need to be updated

**Comment by tfoote** [comment]
Yeah, we can't update a link from an archive. Closing.
