### ISSUE TITLE
Broken Link:https://index.ros.org/doc/ros2/Installation/Eloquent/Windows-Install-Binary/

### ISSUE THREAD

**Issue by greenonline** [ros-infrastructure/rosindex#383]
### 404 Page URL

https://index.ros.org/doc/ros2/Installation/Eloquent/Windows-Install-Binary/

### Referrer URL

https://robotics.stackexchange.com/a/94081/9176

**Comment by CursedRock17** [comment]
The original author of the reply updated the link to display the correct link, this issue can be closed.

**Comment by clalancette** [comment]
Thanks!
