### ISSUE TITLE
Broken Link:https://index.ros.org/doc/ros2/

### ISSUE THREAD

**Issue by Li-Tianyi** [ros-infrastructure/rosindex#384]
### 404 Page URL

https://index.ros.org/doc/ros2/

### Referrer URL

RTI Connext Launcher 6.0.1

### Description

RTI Connext Launcher 6.0.1 -> Ecosystem tab -> ROS

**Comment by tfoote** [comment]
That was retired in 2021 please ticket the RTI Connect Launcher to update their links.

https://discourse.ros.org/t/index-ros-org-doc-ros2-is-being-retired/19141
