### ISSUE TITLE
Broken Link:https://index.ros.org/doc/ros2/Installation/Dashing/Linux-Install-Debians/

### ISSUE THREAD

**Issue by walnin** [ros-infrastructure/rosindex#386]
### 404 Page URL

https://index.ros.org/doc/ros2/Installation/Dashing/Linux-Install-Debians/

### Referrer URL

https://index.ros.org/doc/ros2/Installation/Dashing/Linux-Install-Debians/

### Description

I went to the link to see how to install ros2 and it says this is not the site you are looking for

It's not just the link to the ros2 installation guide, it's the same situation with the console installation link
Is it just me?

**Comment by clalancette** [comment]
No, that is the incorrect location for that documentation; it now lives at http://docs.ros.org/en/humble/Installation/Ubuntu-Install-Debians.html .

Can you explain how you got the above links?

**Comment by tfoote** [comment]
Closing this without a correct referrer url to potentiall fix. That content was moved years ago. https://discourse.ros.org/t/index-ros-org-doc-ros2-is-being-retired/19141
