### ISSUE TITLE
Broken Links to Instance Lists in Dependency table

### ISSUE THREAD

**Issue by QuentinTorg** [ros-infrastructure/rosindex#388]
### 404 Page URL

https://index.ros.org/packages/rosbag2

### Referrer URL

https://index.ros.org/p/ros_base/github-ros2-variants/#jazzy-deps

### Description

clicking on the little number next to the dependency names in the left window results in a broken link. The package name itself to the right of this does have a working link

**Comment by rkent** [comment]
This is pretty universal, the numbers all seem to have the wrong link.

I believe this comes from:
```html
<a href="{{site.baseurl}}/packages/{{p[0]}}" 
```
in ```_includes/package_body.html```.

**Comment by rkent** [comment]
Why is there a link attached to this number at all? I suppose it might be useful if there are multiple instances of the package. But there is no page that you can go to AFAICT that will show you a list of the package instances.

On the package page, there is a dropdown that shows the list of repository instances for a package. For example, if you go to https://index.ros.org/p/grid_map/#iron and you click on the repo name "GITHUB-ANYBOTICS-GRID_MAP" you get a dropdown showing a list of repo instances for this package. If there is anything useful to link to on the number showing how many instances, this is probably it.

I'm not sure though that there really is much interest in this. It would be easier either to give no link on the number, or simply link to that package (which is already linked in multiple places on the line).

**Comment by tfoote** [comment]
The original intent of the index design was to include indexing of forks. So packages can be found in multiple repositories. For example geometry2 is in 3 different repos: 
![image](https://github.com/user-attachments/assets/b6968bcc-aab6-4a94-baac-06a889ba0f48)

I've been slowly backing this out It looks like this was missed in the cleanup of #281 which is trying to help keep the sight slimmer. The repo specific package pages would be good to clean up too. I think that whole column should now be eliminated.

**Comment by tfoote** [comment]
Woops, wrong button, reopening
