### ISSUE TITLE
Non-Markdown non-ReST files

### ISSUE THREAD

**Issue by hidmic** [ros-infrastructure/rosindex#39]
We have an instance of a community contributed `.asciidoc` file in [ros2/ros2_documentation](https://github.com/ros2/ros2_documentation) that's not rendering properly on rosindex. Should we support other file formats? Should we ensure no custom format documentation is pushed into the repo?

**Comment by tfoote** [comment]
I'd rather not grow the scope of what we support. We already support rst and markdown lets stick with that and just convert that file to one of those.

**Comment by hidmic** [comment]
Perfect. I was unsure on how to proceed, since it was apparently provided by a third party.

**Comment by hidmic** [comment]
Closing this one.
