### ISSUE TITLE
Broken Link:https://index.ros.org/doc/ros2/Installation/Foxy/Linux-Development-Setup/

### ISSUE THREAD

**Issue by ahmet-f-gumustas** [ros-infrastructure/rosindex#391]
### 404 Page URL

https://index.ros.org/doc/ros2/Installation/Foxy/Linux-Development-Setup/

### Referrer URL

https://index.ros.org/doc/ros2/Installation/Foxy/Linux-Development-Setup/

### Description

This link is broken

**Comment by CursedRock17** [comment]
Could you put the link/website which provided: https://index.ros.org/doc/ros2/Installation/Foxy/Linux-Development-Setup

So we can find and solve what's causing the issue.


Edit: Also this is probably the link you're looking for: https://docs.ros.org/en/foxy/Installation/Ubuntu-Install-Debians.html

That being said it's for Foxy which is end of life, the latest version would be Jazzy: 

https://docs.ros.org/en/jazzy/Installation/Ubuntu-Install-Debians.html

**Comment by tfoote** [comment]
Closing this without a referrer link that can be fixed.
