### ISSUE TITLE
Broken Link:https://index.ros.org/doc/ros2/Tutorials/Configuring-ROS2-Environment/#source-the-setup-files

### ISSUE THREAD

**Issue by vkmb** [ros-infrastructure/rosindex#398]
### 404 Page URL

https://index.ros.org/doc/ros2/Tutorials/Configuring-ROS2-Environment/#source-the-setup-files

### Referrer URL

https://github.com/RobotWebTools/rclnodejs/blob/develop/README.md

**Comment by CursedRock17** [comment]
Odds are, this is the [link](https://docs.ros.org/en/jazzy/Tutorials/Beginner-CLI-Tools/Configuring-ROS2-Environment.html#source-the-setup-files) that you need for the installation, but in the most recent [jazzy](https://docs.ros.org/en/jazzy/Releases.html) distribution. I have put in an issue with the correct link in the original repository to have this fixed. If I sent the correct link for you, we can close this up.

**Comment by tfoote** [comment]
Closing with fix from @CursedRock17 in https://github.com/RobotWebTools/rclnodejs/issues/977
