### ISSUE TITLE
Broken Link:https://index.ros.org/p/hri_skeletons

### ISSUE THREAD

**Issue by lindsaymichels** [ros-infrastructure/rosindex#399]
### 404 Page URL

https://index.ros.org/p/hri_skeletons

### Referrer URL

https://wiki.ros.org/hri_skeletons

### Description

Broken

**Comment by CursedRock17** [comment]
Assuming this package was [archived in 2022](https://github.com/ros4hri/hri_skeletons/tree/master) and never updated to a ROS 2 distribution, there would be decent enough reason for it not to have been added to index.ros.org. If you're looking for a more updated version of the package in a stable ROS 2 distribution, I would figure [hri_fullbody](https://github.com/ros4hri/hri_fullbody) is a more fitting package. 

Though some of the packages from hri are [on index.ros.org](https://index.ros.org/search/?term=hri), adding more packages seems like a decision the HRI team would have to make.

**Comment by tfoote** [comment]
There's no current releases of that content so it is not in the index. There are good suggestions from above for alternatives.
