### ISSUE TITLE
Broken Link:https://index.ros.org/doc/ros2/

### ISSUE THREAD

**Issue by preethamchinnu** [ros-infrastructure/rosindex#400]
### 404 Page URL

https://index.ros.org/doc/ros2/

### Referrer URL

https://index.ros.org/doc/ros2/

### Description

The link is not working

**Comment by CursedRock17** [comment]
Could you provide a link that took you to the broken index.ros.org so that we can find you the correct link, then patch the broken one.

**Comment by tfoote** [comment]
Closing this as it cannot be fixed without the referrer correctly filled out. 

That url pattern was retired a few years ago: https://discourse.ros.org/t/index-ros-org-doc-ros2-is-being-retired/19141
