### ISSUE TITLE
Broken Link:https://index.ros.org/doc/ros2/Tutorials/Building-Realtime-rt_preempt-kernel-for-ROS-2/

### ISSUE THREAD

**Issue by fuch1m** [ros-infrastructure/rosindex#401]
### 404 Page URL

https://index.ros.org/doc/ros2/Tutorials/Building-Realtime-rt_preempt-kernel-for-ROS-2/

### Referrer URL

https://github.com/ros-realtime/linux-real-time-kernel-builder?tab=readme-ov-file

**Comment by CursedRock17** [comment]
When it comes to creating a rt_preempt kernel, the latest version of this tutorial would be this link in the jazzy docs:
https://docs.ros.org/en/jazzy/Tutorials/Miscellaneous/Building-Realtime-rt_preempt-kernel-for-ROS-2.html

As far as solving this, I have added an issue in the repository where this was found. I hope this was the correct solution for you, if it was, we can go ahead and close this issue

**Comment by fuch1m** [comment]
Thank you for update. From my side the issue can be closed.
