### ISSUE TITLE
Broken Link:https://index.ros.org/doc/ros2/Installation/Dashing/

### ISSUE THREAD

**Issue by M1NKrft** [ros-infrastructure/rosindex#403]

**Comment by CursedRock17** [comment]
Hey @M1NKrft if you could link the exact url that provided you with: https://index.ros.org/doc/ros2/Installation/Dashing/  
that would be great so we could prevent this from happening to others.

In regards to the solution the following link would be the docs.ros equivalent:
https://docs.ros.org/en/dashing/Installation.html

Though I will say that dashing has been [EOL](https://docs.ros.org/en/jazzy/Releases.html) as of 2021 and would recommend using the most recent [distribution: Jazzy](https://docs.ros.org/en/jazzy/Installation.html)

**Comment by tfoote** [comment]
Closing do to no reference link
