### ISSUE TITLE
rosdistro is not being updated

### ISSUE THREAD

**Issue by rkent** [ros-infrastructure/rosindex#404]
If you have an existing rosindex that has been around for awhile, then it will have an existing _remotes/rosdep git repository locally. That repository is not being updated by rosindex.

The code that is supposed to do this IIUC is vnc in the makefile:
```make
prepare-sources:
	mkdir -p $(remotes_dir)
	vcs import --input $(remotes_file) --force $(remotes_dir)
```
If I run this locally on my system, here is the output that I get:
```
kent@ubug15 (ros2):~/github/rkent/rosindex$ vcs import --input _data/remotes.yml --force _remotes
/usr/bin/vcs:6: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import load_entry_point
..
=== _remotes/rosdep (git) ===

Already on 'master'
Your branch is behind 'origin/master' by 1927 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
=== _remotes/rosdistro (git) ===

Already on 'master'
Your branch is behind 'origin/master' by 1927 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
```
If I look at _remotes/rosdep I can see that it is indeed way behind the origin. So it seems like vcs is expecting us pull to that repository, but I see no evidence that this happens.

The symptom I got was there was no listed repos or packages for jazzy, as that was all added after I first ran rosindex locally. The workaround is to remove the _remotes directory before running rosindex.

**Comment by tfoote** [comment]
Can you check #411 fixes it for you?
