### ISSUE TITLE
Broken Link:https://index.ros.org/doc/ros2/Troubleshooting/Installation-Troubleshooting/#import-failing-without-library-present-on-the-system

### ISSUE THREAD

**Issue by videh25** [ros-infrastructure/rosindex#407]
### 404 Page URL

https://index.ros.org/doc/ros2/Troubleshooting/Installation-Troubleshooting/#import-failing-without-library-present-on-the-system

### Referrer URL

From an internal ros2 error

### Description

ModuleNotFoundError: No module named 'rclpy._rclpy'
The C extension '/opt/ros/foxy/lib/python3.8/site-packages/rclpy/_rclpy.cpython-39-x86_64-linux-gnu.so' isn't present on the system. Please refer to 'https://index.ros.org/doc/ros2/Troubleshooting/Installation-Troubleshooting/#import-failing-without-library-present-on-the-system' for possible solutions

**Comment by clalancette** [comment]
Yeah, that's a problem.  But since Foxy is EOL, we aren't going to update it to the new URL.  I'm going to suggest you try a newer release of ROS 2; both Humble (on Ubuntu 22.04) and Jazzy (on Ubuntu 24.04) are supported, and should have this particular issue fixed.
