### ISSUE TITLE
Broken Link:https://index.ros.org/p/stomp_motion_planner

### ISSUE THREAD

**Issue by mosfet80** [ros-infrastructure/rosindex#408]
### 404 Page URL

https://index.ros.org/p/stomp_motion_planner

### Referrer URL

https://wiki.ros.org/stomp_motion_planner

**Comment by CursedRock17** [comment]
I believe the MoveIT project took control of the STOMP motion planner as seen by their latest docs here:
https://moveit.picknik.ai/humble/doc/examples/stomp_planner/stomp_planner_tutorial.html

**Comment by tfoote** [comment]
Yeah, it looks to be released under a different name which is why the speculative cross reference is incorrect. 

https://index.ros.org/p/moveit_planners_stomp/
