### ISSUE TITLE
Broken Link:https://index.ros.org/doc/ros2/Concepts

### ISSUE THREAD

**Issue by gken1985** [ros-infrastructure/rosindex#410]
### 404 Page URL

https://index.ros.org/doc/ros2/Concepts

### Referrer URL

https://ubuntu.com/tutorials/getting-started-with-ros-2#9-conclusion

**Comment by tfoote** [comment]
There's a fix to the link proposed on the upstream document here: https://discourse.ubuntu.com/t/getting-started-with-ros-2/17847/4 I don't know who would have access to edit it.

**Comment by tfoote** [comment]
Duplicate #371
