### ISSUE TITLE
Broken Link:https://index.ros.org/p/full_coverage_path_planner

### ISSUE THREAD

**Issue by ymollard** [ros-infrastructure/rosindex#412]
### 404 Page URL

https://index.ros.org/p/full_coverage_path_planner

### Referrer URL

http://wiki.ros.org/full_coverage_path_planner

### Description

That's the link about FCPP-on-ROS-2:
[See full_coverage_path_planner on index.ros.org for more info including aything ROS 2 related.](https://index.ros.org/p/full_coverage_path_planner)

[FCPP repo](https://github.com/nobleo/full_coverage_path_planner/tree/ros2?tab=readme-ov-file#full-coverage-path-planner-fcpp) says "Migration to ros2 in progress..." but I am not sure whether there is an actual ROS 2 port.

**Comment by tfoote** [comment]
The full_coverage_path_planner doesn't appear to have been submited to the rosdistro: https://github.com/search?q=repo%3Aros%2Frosdistro%20full_coverage_path_planner&type=code

Please suggest to the maintainer to submit it for indexing there. And once it's in the rosdistro (even as just a source entry) it will appear in rosindex.
