### ISSUE TITLE
Enable and/or implement disabled features

### ISSUE THREAD

**Issue by hidmic** [ros-infrastructure/rosindex#42]
There're many disabled entries and missing details across the site we'd like to have available. But before doing anything, we should assess what's there, what's not and how hard would it be to add the missing bits in each case.

**Comment by hidmic** [comment]
@apojomovsky would you do assessment?

**Comment by apojomovsky** [comment]
Disabled features:

- In Package Overview ([example](https://ros-infrastructure.github.io/index.ros.org/p/rviz_common/)):
    - Link to package's ROS Wiki entry is disabled (Seems like the "Website" link under the "Aditional links" block usually points to the Wiki already)
    - Link to roseco is disabled (Data scraper and interactive visualization for the ROS package ecosystem).
- In the "Index" drop-down button from the menu, the following items are currently disabled:
    - Nodes
    - Messages
    - Services
    - Plugins
- In the "Doc" drop-down button from the menu, the following items are currently disabled:
    - Categories
    - Tutorials
    - Readmes
    - APIs
- In the "Contribute" page
    - The green button "Add a repository fork to the index" is disabled

FYI @hidmic

**Comment by hidmic** [comment]
Thanks @apojomovsky. Per discussion with @tfoote, we'll put this one on hold for now.
