### ISSUE TITLE
Broken Link:https://index.ros.org/doc/ros2/Tutorials/#tutorials

### ISSUE THREAD

**Issue by Prajwal-Bandihal** [ros-infrastructure/rosindex#428]
### 404 Page URL

https://index.ros.org/doc/ros2/Tutorials/#tutorials

### Referrer URL

https://index.ros.org/doc/ros2/Tutorials/#tutorials

### Description

the link says "This isn't the page you're looking for...
Move along."

**Comment by tfoote** [comment]
Closing this as there's no reference as to where the referrer URL is. The Referrer URL should be the one that you followed to get to the 404 which is what needs to be fixed. That content has been moved to docs.ros.org https://docs.ros.org/en/rolling/Tutorials.html
