### ISSUE TITLE
Broken Link:https://index.ros.org/doc/ros2/Releases/

### ISSUE THREAD

**Issue by android-rain** [ros-infrastructure/rosindex#434]
### 404 Page URL

https://index.ros.org/doc/ros2/Releases/

### Referrer URL

https://wiki.ros.org/Distributions

### Description

link error

**Comment by tfoote** [comment]
Thanks for the report. I fixed the link in the wiki: https://wiki.ros.org/action/diff/Distributions?action=diff&rev1=112&rev2=113
