### ISSUE TITLE
Broken Link :https://index.ros.org/doc/ros2/Tutorials/Writing-A-Simple-Cpp-Publisher-And-Subscriber/

### ISSUE THREAD

**Issue by paulaperezpalacios** [ros-infrastructure/rosindex#436]
### 404 Page URL

https://index.ros.org/doc/ros2/Tutorials/Writing-A-Simple-Cpp-Publisher-And-Subscriber/

### Referrer URL

https://www.youtube.com/watch?v=Z-lVEcqZvuM

### Description

I was trying to understand how to publish in ros2 from a an android app and I found this link in a youtube videotutorial but unfortunately it is broken

**Comment by tfoote** [comment]
I commented with the updated link on the video.
