### ISSUE TITLE
Broken Link:https://index.ros.org//doc/ros2/Tutorials/Ament-CMake-Documentation/#building-a-library

### ISSUE THREAD

**Issue by jwdinius** [ros-infrastructure/rosindex#441]
### 404 Page URL

https://index.ros.org//doc/ros2/Tutorials/Ament-CMake-Documentation/#building-a-library

### Referrer URL

https://answers.ros.org/question/372164/ament_export_targets-vs-ament_export_interfaces/

### Description

I tried to follow the link from answers.ros.org and was redirected to the 404 page.

**Comment by tfoote** [comment]
That site is in archive now. It should be redirected to https://robotics.stackexchange.com/questions/98348/ament-export-targets-vs-ament-export-interfaces soon. I've updated the link there.
