### ISSUE TITLE
Broken Link:https://index.ros.org/doc/ros2/

### ISSUE THREAD

**Issue by Toutpiot** [ros-infrastructure/rosindex#442]
### 404 Page URL

https://index.ros.org/doc/ros2/

### Referrer URL

https://github.com/Kiloreux/awesome-robotics?tab=readme-ov-file

### Description

<html>
<body>
<header class="site-header" style="box-sizing: border-box; display: block; border-top: 5px solid rgb(66, 66, 66); border-bottom: 1px solid rgb(232, 232, 232); min-height: 56px; position: relative; color: rgb(85, 85, 85); font-family: &quot;Source Sans Pro&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="wrapper" style="box-sizing: border-box; max-width: 1920px; margin-right: auto; margin-left: auto; padding-right: 0px; padding-left: 0px;"><div class="container-fluid" style="box-sizing: border-box; margin-right: auto; margin-left: auto; padding-left: 15px; padding-right: 15px; margin-bottom: 10px;"><div align="center" style="box-sizing: border-box;">
ROS Resources: Documentation \| Support \| Discussion Forum \| Service Status \| ros @ Robotics Stack Exchange
--

</div><div class="row" style="box-sizing: border-box; margin-left: -15px; margin-right: -15px;"><div class="col-sm-12 col-md-9" style="box-sizing: border-box; position: relative; min-height: 1px; padding-left: 15px; padding-right: 15px; float: left; width: 1140px; margin-top: 8px;"><div class="row" style="box-sizing: border-box; margin-left: -15px; margin-right: -15px;"><div class="col-xs-12 col-sm-3 col-md-3" style="box-sizing: border-box; position: relative; min-height: 1px; padding-left: 15px; padding-right: 15px; float: left; width: 285px; white-space: nowrap;"><a class="site-title" href="https://index.ros.org/" style="box-sizing: border-box; background-color: transparent; color: rgb(66, 66, 66); text-decoration: none; font-size: 26px; letter-spacing: -1px;">ROS Index</a></div><div class="col-xs-12 col-sm-9 col-md-9 text-right" style="box-sizing: border-box; text-align: right; position: relative; min-height: 1px; padding-left: 15px; padding-right: 15px; float: left; width: 855px;"><ul class="list-inline" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding-left: 0px; list-style: none; margin-left: -5px;"><li style="box-sizing: border-box; display: inline-block; padding-left: 5px; padding-right: 5px;"><a class="btn btn-link" href="https://index.ros.org/about" style="box-sizing: border-box; background-color: transparent; color: rgb(21, 140, 186); text-decoration: none; display: inline-block; margin-bottom: 0px; font-weight: bold; text-align: center; vertical-align: middle; touch-action: manipulation; cursor: pointer; background-image: none; border-width: 0px 1px 4px; border-style: solid; border-color: transparent; border-image: initial; white-space: nowrap; padding: 9px 12px 7px; font-size: 12px; line-height: 1.42857; border-radius: 0px; user-select: none; box-shadow: none; text-transform: uppercase;">About</a></li><span> </span><li class="dropdown" style="box-sizing: border-box; position: relative; display: inline-block; padding-left: 5px; padding-right: 5px;"><button id="dLabel" class="btn btn-link" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="box-sizing: border-box; color: rgb(21, 140, 186); font-style: inherit; font-variant: inherit; font-weight: bold; font-stretch: inherit; font-size: 12px; line-height: 1.42857; font-family: inherit; font-optical-sizing: inherit; font-size-adjust: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px; overflow: visible; text-transform: uppercase; appearance: button; cursor: pointer; display: inline-block; text-align: center; vertical-align: middle; touch-action: manipulation; background-image: none; border-width: 0px 1px 4px; border-style: solid; border-color: transparent; border-image: initial; white-space: nowrap; padding: 9px 12px 7px; border-radius: 0px; user-select: none; background-color: transparent; box-shadow: none;">Index<span> </span><span class="caret" style="box-sizing: border-box; display: inline-block; width: 0px; height: 0px; margin-left: 0px; vertical-align: middle; border-top: 4px solid; border-right: 4px solid transparent; border-left: 4px solid transparent;"></span></button></li><span> </span><li style="box-sizing: border-box; display: inline-block; padding-left: 5px; padding-right: 5px;"><a class="btn btn-link" href="https://index.ros.org/contribute" style="box-sizing: border-box; background-color: transparent; color: rgb(21, 140, 186); text-decoration: none; display: inline-block; margin-bottom: 0px; font-weight: bold; text-align: center; vertical-align: middle; touch-action: manipulation; cursor: pointer; background-image: none; border-width: 0px 1px 4px; border-style: solid; border-color: transparent; border-image: initial; white-space: nowrap; padding: 9px 12px 7px; font-size: 12px; line-height: 1.42857; border-radius: 0px; user-select: none; box-shadow: none; text-transform: uppercase;">Contribute</a></li><span> </span><li style="box-sizing: border-box; display: inline-block; padding-left: 5px; padding-right: 5px;"><a class="btn btn-link" href="https://index.ros.org/stats" style="box-sizing: border-box; background-color: transparent; color: rgb(21, 140, 186); text-decoration: none; display: inline-block; margin-bottom: 0px; font-weight: bold; text-align: center; vertical-align: middle; touch-action: manipulation; cursor: pointer; background-image: none; border-width: 0px 1px 4px; border-style: solid; border-color: transparent; border-image: initial; white-space: nowrap; padding: 9px 12px 7px; font-size: 12px; line-height: 1.42857; border-radius: 0px; user-select: none; box-shadow: none; text-transform: uppercase;">Stats</a></li></ul></div></div></div><div class="col-sm-12 col-md-3" style="box-sizing: border-box; position: relative; min-height: 1px; padding-left: 15px; padding-right: 15px; float: left; width: 380px; margin-top: 12px;"><form id="top-searchbox" action="https://index.ros.org/search/" role="form" method="get" style="box-sizing: border-box;"><div class="input-group input-group-sm" style="box-sizing: border-box; position: relative; display: table; border-collapse: separate;"><input type="text" class="form-control" name="term" placeholder="Search ROS" style="box-sizing: border-box; color: rgb(85, 85, 85); font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; font-size: 12px; line-height: 1.5; font-family: inherit; font-optical-sizing: inherit; font-size-adjust: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px; display: table-cell; width: 284.8px; height: 28px; padding: 4px 10px; background-color: rgb(255, 255, 255); background-image: none; border: 1px solid rgb(231, 231, 231); border-radius: 2px 0px 0px 2px; box-shadow: rgba(0, 0, 0, 0.075) 0px 2px 0px inset; transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out; position: relative; z-index: 2; float: left;"><span class="input-group-btn" style="box-sizing: border-box; display: table-cell; width: 65.2px; white-space: nowrap; vertical-align: middle; position: relative; font-size: 0px;"><button class="btn btn-default btn-sm" title="Search ROS" type="submit" style="box-sizing: border-box; color: rgb(85, 85, 85); font-style: inherit; font-variant: inherit; font-weight: bold; font-stretch: inherit; font-size: 12px; line-height: 1.5; font-family: inherit; font-optical-sizing: inherit; font-size-adjust: inherit; font-kerning: inherit; font-feature-settings: inherit; font-variation-settings: inherit; margin: 0px 0px 0px -1px; overflow: visible; text-transform: uppercase; appearance: button; cursor: pointer; display: inline-block; text-align: center; vertical-align: middle; touch-action: manipulation; background-image: none; border-width: 0px 1px 4px; border-style: solid; border-color: rgb(226, 226, 226); border-image: initial; white-space: nowrap; padding: 4px 10px; border-radius: 0px; user-select: none; background-color: rgb(238, 238, 238); position: relative; height: 28px;"><span class="glyphicon glyphicon-search" style="box-sizing: border-box; position: relative; top: 1px; display: inline-block; font-family: &quot;Glyphicons Halflings&quot;; font-style: normal; font-weight: normal; line-height: 1; -webkit-font-smoothing: antialiased;"></span></button><span> </span><a href="https://lunrjs.com/guides/searching.html" title="Help to Search" class="btn btn-default btn-sm" style="box-sizing: border-box; background-color: rgb(238, 238, 238); color: rgb(85, 85, 85); text-decoration: none; display: inline-block; margin-bottom: 0px; font-weight: bold; text-align: center; vertical-align: middle; touch-action: manipulation; cursor: pointer; background-image: none; border-width: 0px 1px 4px; border-style: solid; border-color: rgb(226, 226, 226); border-image: initial; white-space: nowrap; padding: 4px 10px; font-size: 12px; line-height: 1.5; border-radius: 0px 2px 2px 0px; user-select: none; text-transform: uppercase; position: relative; height: 28px; margin-left: -1px;"><span class="glyphicon glyphicon-question-sign" style="box-sizing: border-box; position: relative; top: 1px; display: inline-block; font-family: &quot;Glyphicons Halflings&quot;; font-style: normal; font-weight: normal; line-height: 1; -webkit-font-smoothing: antialiased;"></span></a></span></div></form></div></div></div></div></header><div class="page-content" style="box-sizing: border-box; padding: 0px; color: rgb(85, 85, 85); font-family: &quot;Source Sans Pro&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="wrapper" style="box-sizing: border-box; max-width: 1920px; margin-right: auto; margin-left: auto; padding-right: 0px; padding-left: 0px;"><div class="container-fluid" style="box-sizing: border-box; margin-right: auto; margin-left: auto; padding-left: 15px; padding-right: 15px; margin-top: 20px;"><div class="container-fluid" style="box-sizing: border-box; margin-right: auto; margin-left: auto; padding-left: 15px; padding-right: 15px;"><div class="row" style="box-sizing: border-box; margin-left: -15px; margin-right: -15px;"><div class="well" style="box-sizing: border-box; min-height: 20px; padding: 19px; margin-bottom: 20px; background-color: rgb(238, 238, 238); border: 1px solid rgb(231, 231, 231); border-radius: 4px; box-shadow: rgba(0, 0, 0, 0.05) 0px 2px 0px inset;"><div class="container-fluid" style="box-sizing: border-box; margin-right: auto; margin-left: auto; padding-left: 15px; padding-right: 15px;"><div class="row" style="box-sizing: border-box; margin-left: -15px; margin-right: -15px;"><div class="col-md-6" style="box-sizing: border-box; position: relative; min-height: 1px; padding-left: 15px; padding-right: 15px; float: left; width: 725.2px;"><img width="320" src="https://index.ros.org/assets/404_icon.png" style="box-sizing: border-box; border: 0px; vertical-align: middle; max-width: 100%;"></div><div class="col-md-6" style="box-sizing: border-box; position: relative; min-height: 1px; padding-left: 15px; padding-right: 15px; float: left; width: 725.2px;"><h1 style="box-sizing: border-box; font-size: 36px; margin: 20px 0px 10px; font-family: inherit; font-weight: 400; line-height: 1.1; color: rgb(51, 51, 51);">This isn't the page you're looking for...</h1><h2 style="box-sizing: border-box; font-family: inherit; font-weight: 400; line-height: 1.1; color: rgb(51, 51, 51); margin-top: 20px; margin-bottom: 10px; font-size: 30px;">Move along.</h2></div></div></div></div><div class="container-fluid" style="box-sizing: border-box; margin-right: auto; margin-left: auto; padding-left: 15px; padding-right: 15px;"><div class="row" style="box-sizing: border-box; margin-left: -15px; margin-right: -15px;"><div class="col-xs-offset-3 col-xs-6 text-center" style="box-sizing: border-box; text-align: center; position: relative; min-height: 1px; padding-left: 15px; padding-right: 15px; float: left; width: 745px; margin-left: 372.5px;">Did you get here from a link on ROS Index?</div></div><div class="row" style="box-sizing: border-box; margin-left: -15px; margin-right: -15px;"> </div><div class="row" style="box-sizing: border-box; margin-left: -15px; margin-right: -15px;"><div class="col-xs-offset-3 col-xs-6 text-center" style="box-sizing: border-box; text-align: center; position: relative; min-height: 1px; padding-left: 15px; padding-right: 15px; float: left; width: 745px; margin-left: 372.5px;"><a id="github_issue_link" target="_blank" href="https://github.com/ros-infrastructure/rosindex/issues/new?labels=bug&amp;template=form404.yml&amp;title=Broken+Link:https%3A%2F%2Findex.ros.org%2Fdoc%2Fros2%2F&amp;404page=https%3A%2F%2Findex.ros.org%2Fdoc%2Fros2%2F&amp;referrer=https%3A%2F%2Fgithub.com%2FKiloreux%2Fawesome-robotics%3Ftab%3Dreadme-ov-file" class="btn btn-sm btn-default btn-block" style="box-sizing: border-box; background-color: rgb(238, 238, 238); color: rgb(85, 85, 85); text-decoration: none; display: block; margin-bottom: 0px; font-weight: bold; text-align: center; vertical-align: middle; touch-action: manipulation; cursor: pointer; background-image: none; border-width: 0px 1px 4px; border-style: solid; border-color: rgb(226, 226, 226); border-image: initial; white-space: nowrap; padding: 6px 10px 4px; font-size: 12px; line-height: 1.5; border-radius: 2px; user-select: none; width: 715px; text-transform: uppercase;">Report Broken Link</a></div></div><div class="row" style="box-sizing: border-box; margin-left: -15px; margin-right: -15px;"> </div></div></div></div></div></div></div><footer class="site-footer" style="box-sizing: border-box; display: block; border-top: 1px solid rgb(232, 232, 232); padding: 20px 0px; color: rgb(85, 85, 85); font-family: &quot;Source Sans Pro&quot;, &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="wrapper" style="box-sizing: border-box; max-width: 1920px; margin-right: auto; margin-left: auto; padding-right: 0px; padding-left: 0px;"><div class="container-fluid" style="box-sizing: border-box; margin-right: auto; margin-left: auto; padding-left: 15px; padding-right: 15px;"><div class="row" style="box-sizing: border-box; margin-left: -15px; margin-right: -15px;"><div class="col-sm-4 col-md-4" style="box-sizing: border-box; position: relative; min-height: 1px; padding-left: 15px; padding-right: 15px; float: left; width: 506.663px;"><a href="https://github.com/ros-infrastructure/rosindex" title="Find rosindex in Github" style="box-sizing: border-box; background-color: transparent; color: rgb(21, 140, 186); text-decoration: none;"><span class="icon  icon--github" style="box-sizing: border-box;"><svg viewBox="0 0 16 16"><path fill="#828282" d="M7.999,0.431c-4.285,0-7.76,3.474-7.76,7.761 c0,3.428,2.223,6.337,5.307,7.363c0.388,0.071,0.53-0.168,0.53-0.374c0-0.184-0.007-0.672-0.01-1.32 c-2.159,0.469-2.614-1.04-2.614-1.04c-0.353-0.896-0.862-1.135-0.862-1.135c-0.705-0.481,0.053-0.472,0.053-0.472 c0.779,0.055,1.189,0.8,1.189,0.8c0.692,1.186,1.816,0.843,2.258,0.645c0.071-0.502,0.271-0.843,0.493-1.037 C4.86,11.425,3.049,10.76,3.049,7.786c0-0.847,0.302-1.54,0.799-2.082C3.768,5.507,3.501,4.718,3.924,3.65 c0,0,0.652-0.209,2.134,0.796C6.677,4.273,7.34,4.187,8,4.184c0.659,0.003,1.323,0.089,1.943,0.261 c1.482-1.004,2.132-0.796,2.132-0.796c0.423,1.068,0.157,1.857,0.077,2.054c0.497,0.542,0.798,1.235,0.798,2.082 c0,2.981-1.814,3.637-3.543,3.829c0.279,0.24,0.527,0.713,0.527,1.437c0,1.037-0.01,1.874-0.01,2.129 c0,0.208,0.14,0.449,0.534,0.373c3.081-1.028,5.302-3.935,5.302-7.362C15.76,3.906,12.285,0.431,7.999,0.431z"></path></svg><span> </span></span><span class="username" style="box-sizing: border-box;">ros-infrastructure/rosindex</span><span> </span></a>|<span> </span><em style="box-sizing: border-box;">generated on 2024-10-17</em></div><div class="col-sm-8 col-md-8 text-right" style="box-sizing: border-box; text-align: right; position: relative; min-height: 1px; padding-left: 15px; padding-right: 15px; float: left; width: 1013.33px;"><p class="text" style="box-sizing: border-box; margin: 0px 0px 10px;">a community-maintained index of robotics software |<span> </span><a href="https://index.ros.org/privacy.txt" style="box-sizing: border-box; background-color: transparent; color: rgb(21, 140, 186); text-decoration: none;">privacy</a></p></div></div></div></div></footer>
</body>
</html>ROS Resources: [Documentation](http://docs.ros.org/) | [Support](http://wiki.ros.org/Support) | [Discussion Forum](http://discourse.ros.org/) | [Service Status](http://status.ros.org/) | [ros @ Robotics Stack Exchange](https://robotics.stackexchange.com/questions/tagged/ros)
[ROS Index](https://index.ros.org/)
   
Search ROS
 

This isn't the page you're looking for...
Move along.
Did you get here from a link on ROS Index?
 
 
[ ros-infrastructure/rosindex ](https://github.com/ros-infrastructure/rosindex)| generated on 2024-10-17
a community-maintained index of robotics software | [privacy](https://index.ros.org/privacy.txt)

**Comment by clalancette** [comment]
Thanks for the report.  I've now opened a [pull request](https://github.com/kiloreux/awesome-robotics/pull/74) to fix this.

**Comment by tfoote** [comment]
I'm going to close this as we can't do anything to resolve it more from here.
