### ISSUE TITLE
Broken Link:https://index.ros.org/doc/ros2/Concepts

### ISSUE THREAD

**Issue by harpreetm01** [ros-infrastructure/rosindex#447]
### 404 Page URL

https://index.ros.org/doc/ros2/Concepts

### Referrer URL

https://ubuntu.com/tutorials/getting-started-with-ros-2#1-overview

### Description

the link was supposed to show a companion guide to the [ROS 2 tutorials](https://index.ros.org/doc/ros2/Concepts).

**Comment by tfoote** [comment]
Duplicate #371
