### ISSUE TITLE
Add support for distro specific package independent docs

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/rosindex#45]
In the meeting it was suggested that supporting versioning of the doc independent pages would be valuable.

This would allow us to enable the distro toggle switch for pages like the installation instructions.

Where we currently have one yaml file for the independent repos we could have one independent and one for each distro to allow listing of separate repositories or more likely different branches of the same repository.

Alternatively we could use a standardized branch naming scheme for selection.

**Comment by hidmic** [comment]
Alright, this got tricky fast. The way the distro switch works is incompatible with the way we parse docs. While the former works by rendering everything for each distro on a single page and then using some JS bits and a browser cookie to selectively hide and show content, for the latter we rely entirely on setting up a directory tree structure that Jekyll can crawl.

To make all this work, we would have to:

- have a replica of the distro switch that works differently for docs, OR
- crawl documentation repositories ourselves, building hashes with content per distro we can use, OR
- change the way the distro switch works, moving to a URL based logic (different distro, different url, not like it is right now). This means changing the way all other pages work with it as well.

The neatest it is, the more complex it gets. What would you like to do @tfoote ?

**Comment by hidmic** [comment]
Per discussion with @tfoote and @apojomovsky, we'll be putting this feature on hold as it requires significant restructuring.

**Comment by tfoote** [comment]
We've moved the independent docs off of index.ros.org so we can close this.
