### ISSUE TITLE
Broken Link:https://index.ros.org/doc/ros2/Installation/Dashing/Linux-Install-Debians/

### ISSUE THREAD

**Issue by robot-beep** [ros-infrastructure/rosindex#450]
### 404 Page URL

https://index.ros.org/doc/ros2/Installation/Dashing/Linux-Install-Debians/

### Referrer URL

https://github.com/YDLIDAR/ydlidar_ros2_driver?tab=readme-ov-file

### Description

The link to install ROS 2 doesnt work from the ydlidar Readme MD

**Comment by clalancette** [comment]
This should be fixed by https://github.com/YDLIDAR/ydlidar_ros2_driver/pull/48.

**Comment by robot-beep** [comment]
i see,

Thanks, i'll notify them.

**Comment by tfoote** [comment]
Since this is ticketed upstream. Closing it here.
