### ISSUE TITLE
Broken Link:https://index.ros.org/doc/ros2/Concepts/About-Quality-of-Service-Settings/

### ISSUE THREAD

**Issue by YashasPrabhuu** [ros-infrastructure/rosindex#455]
### 404 Page URL

https://index.ros.org/doc/ros2/Concepts/About-Quality-of-Service-Settings/

### Referrer URL

https://github.com/ros2/ros2_documentation/issues/569

**Comment by clalancette** [comment]
I've now updated the comment, so closing this.
