### ISSUE TITLE
Broken Link:https://index.ros.org/doc/ros2/Installation/Humble/

### ISSUE THREAD

**Issue by Bottlinglineguru** [ros-infrastructure/rosindex#457]
### 404 Page URL

https://index.ros.org/doc/ros2/Installation/Humble/

### Referrer URL

https://github.com/jhiggason/YahBoomG1Tank?tab=readme-ov-file#getting-started

### Description

ROS Install guide Link

**Comment by clalancette** [comment]
Thanks for the info.  I've opened https://github.com/jhiggason/yahboomg1tank/pull/17 to update it.
