### ISSUE TITLE
Look at how to separate build stages for caching/optimization

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/rosindex#61]
We're now taking 90 minutes to build the site which is generally too long and very painful if there an error.

It would be great to make it more of a pipeline process that can be restarted. But each step would need to have clearly defined inputs and outputs. 

As a first step the `fetch` and `build` stages could be separated. After that the build stages and caches could be pulled apart instead of being in just one script.

**Comment by apojomovsky** [comment]
An initial proposal would be to:
Extend the `Makefile` with multiple rules that call `jekyll build` appending an unique `yml` file for each that specify which of the steps should be executed/skipped.

One of those `yml` would look like:
```
# update.yml

skip_discover: true
skip_update: false
skip_scrape: true
skip_search_index: true
```

whereas the Makefile would look like:
```
# Creates directories and downloads remote repositories
download-previous:
	mkdir -p $(deploy_dir)
	mkdir -p $(docs_dir)
	mkdir -p $(remotes_dir)
	vcs import --input $(remotes_file) --force $(remotes_dir)

# Gets the repositories from the rosdistro files, rosdoc rosinstall files, and other sources
discover:
	bundle exec jekyll build --verbose --trace -d $(deploy_dir) --config=$(config_file),$(index_file),$(discover_config)

# Clone/fetch all the repos
update:
	bundle exec jekyll build --verbose --trace -d $(deploy_dir) --config=$(config_file),$(index_file),$(update_config)

# Scrapes all the repos
scrape:
	bundle exec jekyll build --verbose --trace -d $(deploy_dir) --config=$(config_file),$(index_file),$(scrape_config)

# Creates lunr index data
search-index:
	bundle exec jekyll build --verbose --trace -d $(deploy_dir) --config=$(config_file),$(index_file),$(search_config)

# Generates the site executing all the previous steps
build: download-previous discover update scrape search-index
```

This would allow us to break the build into different stages that can be executed independently, with the warning that the intermediate versions of the site might be incomplete unless all the steps are executed.

Thoughts @tfoote , @hidmic ?

**Comment by hidmic** [comment]
@apojomovsky It sounds reasonable to me, though I wonder: shouldn't later stages depend on previous ones? We can tag targets as `.PHONY` to not rely on file timestamps.

**Comment by hidmic** [comment]
Hmm nope, forget what I wrote, that defeats the purpose :). I would move build to the top, though. Mind to make a PR with this?

**Comment by apojomovsky** [comment]
Sure  @hidmic !
