### ISSUE TITLE
Don't reload page when pressing enter on search field

### ISSUE THREAD

**Issue by chapulina** [ros-infrastructure/rosindex#73]
On [/search](https://index.ros.org/search/), the search results are fluidly updated without a progress bar as the query is typed. If the user presses `enter`, the page is reloaded and the search bar shows up again.

I think the nice thing that happens when pressing enter is that the address bar gets updated with `q=search_term`. It would make the interaction more seamless if pressing enter didn't trigger a refresh, but just updated the address bar.

**Comment by hidmic** [comment]
Resolved by #76.
