### ISSUE TITLE
Documentation entry page doesn't have a title

### ISSUE THREAD

**Issue by chapulina** [ros-infrastructure/rosindex#89]
See how only a dot shows on the browser tab:

![pagetitlerosindex](https://user-images.githubusercontent.com/5751272/47452458-32543d00-d77f-11e8-872a-b16bc8558a52.png)

Other pages have a title there. Maybe the entry page is handled different since it comes from the README

**Comment by hidmic** [comment]
Is that a build on top of #88? If so, I think I know what it is...

**Comment by chapulina** [comment]
Yup, it is. Feel free to address on that PR. I ticketed an issue not to hold the PR for too long.

**Comment by hidmic** [comment]
Fixed on #88.
