### ISSUE TITLE
Search is broken

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/rosindex#9]
It looks like cross linked/missing baseurl fixes.

![image](https://user-images.githubusercontent.com/447804/45234113-a0a17680-b289-11e8-8e2d-30f4207a38c3.png)

**Comment by apojomovsky** [comment]
@tfoote a fix for this issue has been just merged as part of #8. Feel free to give it a try to confirm it behaves as expected.

**Comment by tfoote** [comment]
Confirmed it's covered in #8 redeployed with that merged fixes this problem.
