### ISSUE TITLE
Move ROS 2 documentation entry point to /doc/ros2

### ISSUE THREAD

**Issue by chapulina** [ros-infrastructure/rosindex#95]
Right now the entry point is at https://index.ros.org/doc/ros2_overview/. How do you feel about moving this to https://index.ros.org/doc/ros2 for brevity? It feels more natural to me, since that page is more than an "overview", it's actually **the** ROS 2 documentation entry point.

@hidmic @apojomovsky

**Comment by hidmic** [comment]
Sounds good to me, though I think @tfoote argued against at some point. Am I right? If not, nvm, I'll just change the entry name.

**Comment by tfoote** [comment]
I think it makes sense to use the shorter url. This will be the top level ros2 documentation but not all ros2 documentation will go here.

**Comment by hidmic** [comment]
I think we can close this one now.
