### ISSUE TITLE
Sort by last commit date not working?

### ISSUE THREAD

**Issue by chapulina** [ros-infrastructure/rosindex#96]
Clicking on the button to sort packages by last commit date rearranges them in an order which doesn't look correct:

https://index.ros.org/packages/page/1/time/

![sorttime](https://user-images.githubusercontent.com/5751272/47468137-8aeefe80-d7ae-11e8-9a42-1b26d4f8dc38.png)

**Comment by hidmic** [comment]
Hmm I think I know what's going on. Packages are sorted by latest commit date. Literally. No matter the distro that commit applies to. And the column displays the last commit date for the selected distro. That's why you end up with a misleading UI. I wonder if this was intended though.

**Comment by chapulina** [comment]
Since the sorted list is displayed in a per-distro basis, the sorting should take only that distro's commits into account IMO.
