### ISSUE TITLE
Repository page should default to newest available distro

### ISSUE THREAD

**Issue by chapulina** [ros-infrastructure/rosindex#97]
For example, the repository's shortest URL:

https://index.ros.org/r/geometry

Displays Indigo by default, which is equivalent to:

https://index.ros.org/r/geometry/#indigo

What do you think of showing the newest version instead?

**Comment by chapulina** [comment]
Just found some documentation about this [here](https://index.ros.org/about/design/#repository-organization):

> This link would resolve to the repository corresponding to the URI given in the **latest rosdistro index**... Note that the repository for a repository identifier can change between distributions. In this case, it is expected that older versions of the sources are tagged in the latest version of the repository.

But I'm not entirely sure I understand what it means and whether the behaviour I reported above is expected / desired or not.

**Comment by dirk-thomas** [comment]
It should show the latest released ROS distro by default. Since an upcoming release might exist that distro needs to be configured manually somewhere.

**Comment by chapulina** [comment]
Just clarifying, by "latest released" you mean the newest distro, not the most recently synced one, correct?

**Comment by chapulina** [comment]
After some poking around, I found out there's some cookie magic going on and a user is automatically directed to their "preferred" distro, which is just the last distro they've clicked on when visiting the site before.

That's how I ended up on Indigo. But if you're visiting the site for the first time, you'll have no preferred distro (you can see the following printed to the console: `preferring undefined distro`) and then it defaults to `bouncy`, which *is* the latest, so **it works as expected**.

However, you land on `bouncy` even if the package / repository doesn't exist on that distro. So a user navigating to https://index.ros.org/r/geometry/ for the first time sees this, and **that needs to be fixed**.

![bouncypreferred](https://user-images.githubusercontent.com/5751272/47470016-b0810580-d7b8-11e8-8a55-70e3edc85fab.png)

**Comment by dirk-thomas** [comment]
> and then it defaults to bouncy, which is the latest, so it works as expected.

Once we create a Crystal distro I would expect it to choose Crystal by default. But until the actual release date it should continue to use Bouncy as the default.
